packages/leemons-plugin-academic-portfolio/frontend/src/components/SelectSubject.js
packages/leemons-plugin-academic-portfolio/frontend/src/widgets/user-classes-swiper/index.js
packages/leemons-plugin-calendar/frontend/src/widgets/calendar/task.js
packages/leemons-plugin-scores/frontend/src/components/ScoresPage/Filters.js

…ct component
Ref: #issue/BubblesDS-0

Issue/bubbles BulletSubject

---

plugins/leemons-plugin-leebrary/backend/i18n/en.js
plugins/leemons-plugin-leebrary/backend/i18n/es.js
plugins/leemons-plugin-leebrary/frontend/src/pages/private/assets/AssetPage.js
plugins/leemons-plugin-tasks/backend/i18n/en.js
plugins/leemons-plugin-tasks/backend/i18n/es.js
plugins/leemons-plugin-tasks/frontend/src/pages/private/library/TaskSetupPage.js
plugins/leemons-plugin-tests/backend/i18n/en.js
plugins/leemons-plugin-tests/backend/i18n/es.js

Fix subtitle on Library asset creation, Bookmark asset creation and test asset creation

Asset Creation - Total Layout Header - Incoherencias

---

plugins/leemons-plugin-academic-portfolio/backend/i18n/en.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/es.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/SubjectItemDisplay/SubjectItemDisplay.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryCardBody/LibraryCardBody.js

We have added an additional case so that if the subject id comes in an array of strings (as is the case with the preview card), LibraryCardBody will handle parsing the data that comes to SubjectItemDisplay. We have taken advantage of the development to add the text variables to the Multisubject case that were hard coded.

Bookmarks - Error vista previa

---

plugins/leemons-plugin-leebrary/frontend/src/helpers/imageUrlToFile.js
plugins/leemons-plugin-leebrary/frontend/src/pages/private/assets/AssetPage.js
plugins/leemons-plugin-leebrary/frontend/src/request/newAsset.js

Download bookmark url using external api and reupload to Leebrary

fix: Leebrary bookmarks error

---

plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/ModuleDashboard.js

fix styles on module dashboard-resources tab

Module Dashboard - Pestaña de recursos - Nueva maquetación MVP

---

plugins/leemons-plugin-menu-builder/frontend/src/components/mainMenu/index.js
plugins/leemons-plugin-users/backend/services/rest/platform.rest.js
plugins/leemons-plugin-users/frontend/src/request/getPlatformName.js

Added platform name to menu title when is admin.

feat: Added platform name to menu title when is admin.

---

plugins/leemons-plugin-scores/frontend/src/components/Notebook/components/ActivitiesTab/ScoresTable.js
plugins/leemons-plugin-scores/frontend/src/components/StudentScoresPage/Filters.js
plugins/leemons-plugin-scores/frontend/src/components/StudentScoresPage/StudentActivities.js

My Scores - Maquetar con Total Layout la vista de estudiante para tener un MVP Freemium.

---

plugins/leemons-plugin-academic-calendar/frontend/src/helpers/useProcessCalendarConfigForBigCalendar.js

feat(calendar): Change program abbreviation for program name in calendar events.

feat(calendar): Change program abbreviation for program name in calendar events.

---

plugins/leemons-plugin-leebrary/frontend/src/pages/private/library/Library.js

Fix this stange style case. Remove overflow-y to fix it

Task creation - error de maquetación extraño

---

plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardFooter/DashboardCardFooter.constants.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardFooter/DashboardCardFooter.js

If is no evaluabe, don't show "for evaluation" label

Module Dashboard - Estado erróneo de botón para actividad No Evaluable

---

plugins/leemons-plugin-assignables/frontend/src/components/NYACard/NYCardBody/NYACardBody.js
plugins/leemons-plugin-assignables/frontend/src/hooks/assignableInstance/usePendingEvaluationsCount.js
plugins/leemons-plugin-calendar/frontend/src/components/KanbanTaskCard/KanbanTaskCard.constants.js
plugins/leemons-plugin-calendar/frontend/src/components/KanbanTaskCard/KanbanTaskCard.js

Don't show calificable badge if is module card. NYA cards and Kanban cards

LModules - NYA & Kanban Cards - Las cards de módulo no llevan chip de evaluación

---

plugins/leemons-plugin-content-creator/frontend/src/pages/Detail/index.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/Detail/index.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetList.js
plugins/leemons-plugin-tasks/frontend/Private.js
plugins/leemons-plugin-tasks/frontend/src/pages/private/library/TaskSetupPage.js
plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/Detail.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/Edit.js

Replace history.push for history.replace.

feat: implement go back functionality to handle cancel actions in asset creation/editing

---

plugins/leemons-plugin-assignables/backend/validations/validateGrade.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/Result.js

Firstly start using standarized updateStudentRequest to save feedback in tests.
Fix validation error that was causing null scores to be rejected by server. Keep in mind that activities can be of type `feedback only`

fix(tests): save feedback correctly

---

plugins/leemons-plugin-leebrary/backend/i18n/en.js
plugins/leemons-plugin-leebrary/backend/i18n/es.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/components/AssetList/AssetList.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/components/AssetList/components/Header.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/components/AssetList/components/List.js
plugins/leemons-plugin-leebrary/frontend/src/helpers/loadMediaTypes.js
plugins/leemons-plugin-leebrary/frontend/src/pages/private/assets/ListAssetPage.js

- Add media type filter to AssetPickerDrawer for  media-file resources.
- Extract the logic to a helper function in a different file.
- Update ListAssetPage to use the helper function

Library: Add media type filter to AssetPickerDrawer

---

plugins/leemons-plugin-academic-portfolio/frontend/src/widgets/class-detail/index.js

Depends on: [Bubbles #114](https://github.com/leemonade/bubbles/pull/114)

feat(academic-portfolio): add selectable option to class-detail tables

---

plugins/leemons-plugin-menu-builder/frontend/src/components/mainMenu/index.js
plugins/leemons-plugin-users/frontend/src/components/SelectProfile.js
plugins/leemons-plugin-users/frontend/src/pages/protected/SelectProfile/index.js

Improve profile access control by filtering profiles and centers based on deployment configuration. Refactor event handling and eliminate redundant code. Handle empty profile selections gracefully. Optimize performance by simplifying useEffect dependencies.

feat(DeploymentConfig): Improve profile access control

---

plugins/leemons-plugin-assignables/frontend/src/widgets/dashboard/nya/components/EvaluationCardStudent/components/ScoreFeedback.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/Result.js

Waiting for @jjleemons confirmation on behaviour.

fix(tests): use isTeacher hook and initialize feedback from assignation

---

plugins/leemons-plugin-assignables/backend/core/permissions/assignables/users/getUserPermission/getUserPermission.js
plugins/leemons-plugin-assignables/backend/core/permissions/assignables/users/getUserPermissions/getUserPermissions.js
plugins/leemons-plugin-leebrary/backend/core/permissions/set/set.js
plugins/leemons-plugin-leebrary/backend/services/permissions.service.js

fix(assignables): use assets share permissions

---

plugins/leemons-plugin-assignables/backend/core/roles/registerRole.js
plugins/leemons-plugin-content-creator/backend/config/constants.js
plugins/leemons-plugin-leebrary/backend/config/constants.js
plugins/leemons-plugin-leebrary/backend/core/categories/add/add.js
plugins/leemons-plugin-leebrary/backend/i18n/en.js
plugins/leemons-plugin-leebrary/backend/i18n/es.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetList.js
plugins/leemons-plugin-leebrary/frontend/src/components/NewLibraryCardButton/NewLibraryCardButton.js
plugins/leemons-plugin-leebrary/frontend/src/components/NewLibraryCardButton/NewLibraryCardButton.styles.js
plugins/leemons-plugin-leebrary/frontend/src/helpers/getPageItems.js
plugins/leemons-plugin-leebrary/frontend/src/pages/private/library/Library.js
plugins/leemons-plugin-tests/backend/config/constants.js

- Implement pluralName and singularName fields across various plugins for categories.
- Enhance the add function in leemons-plugin-leebrary to support localization of category names.
- Update frontend components to utilize the new localized category names.
- Adjust pagination logic to account for the new item button in lists.

feat(Library): add localization support for category names and New button for asset creation

---

plugins/leemons-plugin-content-creator/frontend/src/components/AssetMetadataContentCreator/AssetMetadataContentCreator.js
plugins/leemons-plugin-content-creator/frontend/src/helpers/extractH1AndH2Content.js
plugins/leemons-plugin-content-creator/frontend/src/helpers/getH1Content.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetList.js

In this branch, we added the H2 headlines to the schema that appears in the detail drawer of the Content Creator items in the Library. Previously, only the H1 headlines appeared.

Main Library - Documents - Student Subject “Folder”

---

packages/leemons-react/src/templates/dev.html
packages/leemons-react/src/templates/prod.html

Favicon added to dev.html and prod.html
The favicon comes from leemons public website

No hay favicon en la plataforma

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/SubjectPicker/SubjectPicker.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleSetup/components/BasicData/BasicData.js
plugins/leemons-plugin-tasks/frontend/src/pages/private/library/TaskSetupPage.js

fix(lModules): Allow agnostic assignable
fix(AcaPortfolio): Do not submit when no subject is selected in SubjectPicker

fix(tasks): Allow agnostic assignable

---

plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/components/Attachments/Attachments.js

replace AssetListDrawer for AssetPickerDrawer in task creation/edition.

fix(tasks): replace AssetListDrawer for AssetPickerDrawer

---

plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/components/Config/components/TypeRenderer/TypeRenderer.js

Related to notion ticket: issue/LModules-54

fix(lModules): error when localizations are not loaded

---

plugins/leemons-plugin-assignables/backend/core/instances/searchInstances/filterByInstanceDates.js
plugins/leemons-plugin-assignables/backend/core/instances/searchInstances/searchInstances.js
plugins/leemons-plugin-assignables/backend/core/ongoing/helpers/activitiesData/getActivitiesDates.js
plugins/leemons-plugin-assignables/backend/core/ongoing/helpers/filters/filterInstancesByStatusAndArchived.js
plugins/leemons-plugin-assignables/frontend/src/components/Ongoing/AssignmentList/AssignmentList.js
plugins/leemons-plugin-assignables/frontend/src/components/Ongoing/AssignmentList/components/ActivitiesList/ActivitiesList.js

fix(assignables): stop using visibility date for students
Finally we are using the visualization date in every place
fix(assignables): main ongoing wrong totalLayout when scrollable

fix(assignables): show scheduled activities on main ongoing to student

---

plugins/leemons-plugin-scores/frontend/src/components/StudentScoresPage/Filters.js
plugins/leemons-plugin-scores/frontend/src/components/StudentScoresPage/StudentActivities.js

fix(scores): show subjects in multi-course programs

feat(scores): show only finished assignations in student scores page

---

plugins/leemons-plugin-deployment-manager/backend/services/rest/deployment-manager.rest.js
plugins/leemons-plugin-menu-builder/backend/i18n/en.js
plugins/leemons-plugin-menu-builder/backend/i18n/es.js
plugins/leemons-plugin-menu-builder/frontend/src/components/MainNavBar/MainNavBar.js
plugins/leemons-plugin-menu-builder/frontend/src/components/MainNavBar/components/LinkWrapper/LinkWrapper.js
plugins/leemons-plugin-menu-builder/frontend/src/components/MainNavBar/components/NavItem/NavItem.js
plugins/leemons-plugin-menu-builder/frontend/src/components/MainNavBar/components/UserButton/UserButton.js
plugins/leemons-plugin-menu-builder/frontend/src/components/mainMenu/index.js

- Implement dynamic helpdesk URL configuration in deployment manager
- Add 'Help Center' menu item in multiple languages
- Enhance navigation by supporting new window targets for links
- Refactor MainMenu to utilize useMemo for deployment configuration

feat: add helpdesk URL support and enhance navigation links

---

plugins/leemons-plugin-content-creator/frontend/src/pages/Detail/index.js

Student can't assign new or editable Document.

C.Creator - Al estudiante le sale la opción de asignar en el documento

---

plugins/leemons-plugin-assignables/backend/i18n/en.js
plugins/leemons-plugin-assignables/backend/i18n/es.js
plugins/leemons-plugin-assignables/frontend/package.json
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/ActivityHeader.constants.js
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/components/Timer/Timer.js
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/components/Timer/Timer.styles.js
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/components/Timer/components/Countdown/Countdown.js
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/index.js
plugins/leemons-plugin-assignables/frontend/src/components/EvaluationFeedback/TimeoutAlert.js
plugins/leemons-plugin-tasks/frontend/src/components/Student/TaskDetail/TaskDetail.js
plugins/leemons-plugin-tasks/frontend/src/components/StudentCorrection/StudentCorrection.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/Result.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/StudentInstance/index.js
yarn.lock

feat(assignables): Add TimeoutAlert component
feat(tasks): Use Countdown in execution
feat(tasks): Handle fromTimeout in Student Correction
feat(tests): Use Countdown in execution
feat(tests): Handle fromTimeout in Correction

feat(assignables): Add Countdown to ActivityHeader

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetSetup/PermissionsData.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetSetup/PermissionsData.styles.js

Shared Drawer - Add Users Tab - Cambio posición advertencia

---

plugins/leemons-plugin-leebrary/frontend/src/components/CardWrapper.js

Bookmarks can't convert to task (Assign)

MainLibrary - Bookmarks - Ocultar la opción de crear tarea desde bookmark

---

plugins/leemons-plugin-board-messages/frontend/src/components/DetailDrawer/DetailDrawer.js
plugins/leemons-plugin-content-creator/frontend/src/widgets/assignables/AssignmentDrawer.js
plugins/leemons-plugin-dataset/frontend/src/components/_DatasetItemDrawer/components/FieldConfigLocale/common/TranslateOptions.js
plugins/leemons-plugin-families/frontend/src/components/SearchUserDrawer/SearchUserDrawer.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/ModuleAssign.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/SetupStep.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/components/ConfigModal/ConfigModal.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetFormInput.js
plugins/leemons-plugin-multilanguage/frontend/src/components/TranslatorModal/TranslatorModal.js
plugins/leemons-plugin-tasks/frontend/src/widgets/assignables/AssignmentDrawer.js
plugins/leemons-plugin-tests/frontend/src/components/AssignConfig.js
plugins/leemons-plugin-tests/frontend/src/widgets/assignables/AssignmentDrawer.js
plugins/leemons-plugin-users/backend/i18n/en.js
plugins/leemons-plugin-users/backend/i18n/es.js
plugins/leemons-plugin-users/frontend/src/pages/public/RegisterPassword/index.js
plugins/leemons-plugin-users/frontend/src/pages/public/Reset/index.js

- Adjust drawer sizes across multiple plugins for UI consistency
- Refactor AssignmentDrawer, ModuleAssign, and ConfigModal components to use new layout and styling approaches
- Introduce PropTypes validation for enhanced component reliability
- Implement success alerts for password setting actions in user plugin
- Optimize filtering logic in AssignConfig component
- Minor code cleanup and removal of unused imports

feat: update drawer sizes and refactor components for consistency

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetList.js
plugins/leemons-plugin-leebrary/frontend/src/components/ListEmpty.js
plugins/leemons-plugin-leebrary/frontend/src/components/SearchEmpty.js
plugins/leemons-plugin-leebrary/frontend/src/helpers/getPageItems.js

Issues solved:
- Empty page with only a create new Item button eliminated
- Deleting the only asset of a page would not come back to the first page leaving a blank page with no pagination controls
- Bring back search by criteria

fix(leebrary): fix pagination issues + bring back search functionality

---

plugins/leemons-plugin-leebrary/frontend/src/components/LibraryNavbar/LibraryNavbar.js
plugins/leemons-plugin-leebrary/frontend/src/pages/private/library/Library.js

- Add default noop handlers for onNav, onFile, and onNew in LibraryNavbar to prevent potential undefined function errors.
- Introduce lodash's capitalize function for category labels to ensure consistent capitalization.
- Replace hardcoded category strings with constants for better maintainability and readability in Library.js.

fix(Library): improve default handlers and category naming

---

plugins/leemons-plugin-leebrary/backend/services/assets.service.js
plugins/leemons-plugin-users/backend/core/platform/getHostname.js
plugins/leemons-plugin-users/backend/core/users/jwt/generateJWTToken.js
plugins/leemons-plugin-users/backend/core/users/reset.js
plugins/leemons-plugin-users/backend/core/users/sendWelcomeEmailToUser.js

- Select the most recent domain for hostname in `getHostname.js`.
- Refactor `generateJWTToken` to return a promise, aligning with async operations.
- Improve error logging in the `reset` function for better debugging.
- Simplify token generation and usage in `sendWelcomeEmailToUser`.

feat(Users): enhance hostname retrieval and error handling

---

plugins/leemons-plugin-assignables/frontend/src/widgets/dashboard/nya/components/EvaluationCardStudent/components/ScoreFeedback.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardCover/DashboardCardCover.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/ScoreFeedback/ScoreFeedback.js

fix(LModules): show score when grade is 0
fix(LModules): remove arrows

fix(LModules): show score feedback when grade is 0

---

plugins/leemons-plugin-scores/frontend/src/components/StudentScoresPage/Filters.js

fix(scores): remove spacing between filters

fix(scores): pick default course when unique course

---

plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/ModuleDashboard.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/DashboardCard.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardBody/DashboardCardBody.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardCover/DashboardCardCover.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardCover/DashboardCardCover.styles.js

fix(DashboadCard): WIP: fix on color bar and refactor on method calls

Module Dashboard - Perdemos el color de la asignatura en las tarjetas

---

plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/ContentData.js
plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/EvaluationData.js

fix(tasks): Do not allow to add custom objectives if no subject is selected
fix(tasks): Add boolean condition to check if subjects are selected
---
notion: task/Tasks-40, issue/Tasks-85

fix(tasks): Handle save event on EvaluationData step

---

plugins/leemons-plugin-tasks/frontend/src/components/Student/TaskDetail/components/SubmissionStep/components/File/File.js

Move the handler to avoid the deletion of non-removed files
fix(tasks): Preserve leebraryID when adding other files
---
Ticket: issue/Tasks-81

refactor(tasks): move submission file deletion handling

---

plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardCover/DashboardCardCover.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/helpers/getOngoingInfo.js

fix(lModules): conditional hook
---
Ticket: issue/LModules-88

fix(lModules): add DashboardCard "someEvaluated" status

---

plugins/leemons-plugin-calendar/backend/config/constants.js
plugins/leemons-plugin-calendar/frontend/src/components/calendar-event-modal.js
plugins/leemons-plugin-calendar/frontend/src/widgets/tab-calendar/index.js
plugins/leemons-plugin-calendar/frontend/src/widgets/user-program-calendar/index.js

add new properties to Calendar in subject dashboard.

Subject Dashboard - Ajustes pestaña “Calendar”

---

plugins/leemons-plugin-menu-builder/frontend/src/components/MainNavBar/components/UserButton/UserButton.styles.js

- Fix the heigh of the menu for accommodate one item more.

Logout perdido en scroll en menú de admin

---

plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardCover/DashboardCardCover.js

Optional chaining added to subjects to prevent blank page on DashboardCardCover.

Error al asignar módulo 

---

plugins/leemons-plugin-assignables/backend/i18n/en.js
plugins/leemons-plugin-assignables/backend/i18n/es.js
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/components/CloseButtons/CloseButtons.js
plugins/leemons-plugin-assignables/frontend/src/components/Details/components/TaskOngoingList/hooks/useTaskOngoingInstanceParser.js
plugins/leemons-plugin-leebrary/backend/i18n/en.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetForm/AssetForm.js
plugins/leemons-plugin-tests/backend/i18n/en.js

Complements: https://github.com/leemonade/leemons-private-plugins/pull/8

feat(transversal): add localization in different plugins + fix urgent english translations 

---

plugins/leemons-plugin-tests/frontend/src/pages/private/tests/Result.style.js

Add maxWidth style property to tableCell to prevent question overflow on test result view.

Test - evaluation page - se desmaqueta si la pregunta es muy larga

---

plugins/leemons-plugin-assignables/frontend/src/components/Details/components/UsersList/helpers/useParseStudents.js

refactor(assignables): extract function declared in useParseStudents
---
Ticket: issue/OnGoing-98

fix(assignables): add missing dependencies to hook useParseStudents

---

plugins/leemons-plugin-tests/backend/i18n/en.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/StudentInstance/components/QuestionValue.js

if user navigate between questions, hint selector must reset his value.

Test - ejecución - hay que re-iniciar el select de pistas entre preguntas

---

plugins/leemons-plugin-users/backend/core/user-agents/getUserDatasetInfo.js
plugins/leemons-plugin-users/backend/services/rest/users.rest.js
plugins/leemons-plugin-users/frontend/src/hooks/useUserDetails.js

- Improve error logging in `getUserDatasetInfo` by including locale information.
- Sanitize `user` and `userAgent` data in `usersService.detailForPage` to exclude sensitive information.

feat(users): Create `useUserDetails` hook and do some data sanitization

---

plugins/leemons-plugin-tasks/frontend/src/components/Correction/Correction.js

fix(tasks): do not overwrite feedback when already touched by teacher

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/components/NewResource.js
plugins/leemons-plugin-leebrary/frontend/src/helpers/compressImage.js
plugins/leemons-plugin-leebrary/frontend/src/helpers/imageUrlToFile.js
plugins/leemons-plugin-leebrary/frontend/src/pages/private/assets/AssetPage.js

- Create helper function to manage this logic
- Update in AssetPage and AssetPickerDrawer when new resources are created.

fix(leebrary): Establish a maximum size for image files to decide whether or not to compress the image.

---

plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/Preview/Preview.js

Fix preview card on assignment view for Tests and Feedback

Tests Asignación - Perdemos el patronus y el label de la tipología del asset

---

plugins/leemons-plugin-academic-portfolio/backend/core/classes/addClass.js
plugins/leemons-plugin-academic-portfolio/backend/core/classes/addClassStudents.js
plugins/leemons-plugin-academic-portfolio/backend/core/classes/addClassTeachers.js
plugins/leemons-plugin-academic-portfolio/backend/core/classes/updateClass.js

Between students and teachers in every classroom

feat(academic-portfolio): Remove automatic room creation

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/SubjectPicker/SubjectPicker.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/ModuleAssign.js

Ticket: task/LModules-45
feat(aPortfolio): Disable SubjectPicker button when input is disabled

feat(lModules): only allow one subject in assignation

---

plugins/leemons-plugin-scores/frontend/src/components/ScoresPage/Filters/Filters.js
plugins/leemons-plugin-scores/frontend/src/components/StudentScoresPage/Filters.js

fix(scores): auto select course dates on student scores

---

plugins/leemons-plugin-content-creator/backend/i18n/en.js

Add documentCard.document to english translations with "Document" value.

C.Creator Library Card - hemos perdido otra vez la etiqueta “Document”

---

plugins/leemons-plugin-assignables/frontend/src/components/Ongoing/AssignmentList/AssignmentList.js

AssignmentList) add paddingTop to section title

Margen en T1 de MainOngoing

---

plugins/leemons-plugin-leebrary/backend/core/permissions/getClassesPermissions/getClassesPermissions.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetSetup/components/PermissionsDataClasses.js
plugins/leemons-plugin-scores/frontend/src/components/ScoresPage/Filters/Filters.js
plugins/leemons-plugin-scores/frontend/src/components/StudentScoresPage/StudentActivities.js

fix(leebrary): Do not assume that a class has groups

fix(scores): Do not assume that a class has groups

---

plugins/leemons-plugin-common/frontend/src/components/ContentEditorInput/components/Schema/Schema.js
plugins/leemons-plugin-common/frontend/src/components/ContentEditorInput/components/Schema/Schema.styles.js

Add correct fontSizes to headers in Schema and create a new style for level 3 headers.

Schema C.Creator - ajustes de maquetación

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/ClassroomPicker/ClassroomPicker.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/ClassroomPicker/helpers/index.js
plugins/leemons-plugin-assignables/backend/emails/UserNewAssignation.jsx
plugins/leemons-plugin-assignables/backend/emails/UserRememberAssignation.jsx
plugins/leemons-plugin-users/backend/core/users/login.js
plugins/leemons-plugin-users/backend/emails/NewProfileAdded.jsx
plugins/leemons-plugin-users/backend/emails/RecoverPassword.jsx
plugins/leemons-plugin-users/backend/emails/ResetPassword.jsx
plugins/leemons-plugin-users/backend/emails/Welcome.jsx
plugins/leemons-plugin-users/frontend/src/components/LoginForm/LoginForm.js
plugins/leemons-plugin-users/frontend/src/pages/public/Login/index.js

- Implement `useLocale` hook to adapt ClassroomPicker based on locale
- Refactor `transformData` function to support locale for day abbreviations
- Update email components to accept `locale` prop for internationalization
- Enhance error handling in `login.js` with more descriptive messages
- Adjust `LoginForm` and `Login` page to improve user experience and error feedback
- Minor code cleanup and reorganization for better readability

feat(academic-portfolio): add locale support to ClassroomPicker

---

plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/components/Attachments/Attachments.js
plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/components/Attachments/AttchmentItem.js

feat(tasks): Add line dividing elements in the table
feat(tasks): Make the bin button icon bigger

feat(tasks): Move add resource button above resource list

---

plugins/leemons-plugin-leebrary/backend/i18n/en.js
plugins/leemons-plugin-leebrary/backend/i18n/es.js
plugins/leemons-plugin-leebrary/frontend/src/components/ImagePicker.js

pass onShowDrawer and new labels to ImagePreviewInput

Asset creation  - Eliminar/cambiar de cover una vez subido

---

plugins/leemons-plugin-tasks/backend/i18n/en.js
plugins/leemons-plugin-tasks/backend/i18n/es.js
plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/EvaluationData.js
plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/components/Objectives.js
plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/components/Objectives.styles.js

Implement the redesign of the Custom Objectives section for the Basic phase.

Task Creation - Evaluation step

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetForm/AssetForm.js

Change ColorInput props to improve color selection.

Color picker antiguo en Content Creator

---

plugins/leemons-plugin-board-messages/backend/core/messages/getOverlapsWithOtherConfigurations.js
plugins/leemons-plugin-board-messages/frontend/src/components/BannerMessage/BannerMessage.js
plugins/leemons-plugin-board-messages/frontend/src/components/BannerMessage/BannerMessage.styles.js
plugins/leemons-plugin-board-messages/frontend/src/components/DetailDrawer/DetailDrawer.constants.js
plugins/leemons-plugin-board-messages/frontend/src/components/DetailDrawer/DetailDrawer.js
plugins/leemons-plugin-board-messages/frontend/src/components/MessagesTable/MessagesTable.js
plugins/leemons-plugin-board-messages/frontend/src/components/MessagesTable/MessagesTable.styles.js
plugins/leemons-plugin-board-messages/frontend/src/components/MessagesTable/components/ActionItem.js
plugins/leemons-plugin-board-messages/frontend/src/components/MessagesTable/components/EmptyState.js
plugins/leemons-plugin-board-messages/frontend/src/pages/private/List/index.js
plugins/leemons-plugin-board-messages/frontend/src/request/save.js
plugins/leemons-plugin-board-messages/frontend/src/widgets/class-dashboard/index.js
plugins/leemons-plugin-board-messages/frontend/src/widgets/dashboard/index.js

This pull request introduces a series of enhancements aimed at improving the message handling and user interface of the message board plugin. Key changes include:
- **Query Logic Improvement**: Replaced `$not` with `$nor` in `getOverlapsWithOtherConfigurations.js` for more accurate query logic.
- **Conditional URL Handling**: Updated `BannerMessage.js` to support URLs with non-http protocols, enhancing flexibility.
- **Layout Enhancements**: Added the `Stack` component to `BannerMessage.js` for better layout structure and implemented background color styling for banner messages.
- **Zone Management**: Introduced `MESSAGE_ZONES` constants for clearer management of message zones.
- **Code Refactoring**: 
- Refactored `DetailDrawer.js` to utilize `omit` for cleaner code and integrated the …

Enhancements to Message Board Handling and UI Components

---

plugins/leemons-plugin-calendar/backend/core/pluginEvents/class/onAcademicPortfolioAddClassTeacher.js

Remove transactions because in try...catch it must not be used.

fix(calendar): remove transactions and add missing resolve

---

plugins/leemons-plugin-content-creator/frontend/src/components/AssetMetadataContentCreator/AssetMetadataContentCreator.styles.js

fix(assetMetadataContentCreator): substract 2px of paddingBottom to hide line break.

Maquetación esquema en drawer de content creator

---

plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/components/question-types/MonoResponse/index.js

fix(QBanks): remove * in Explanation title when user create a new question.

QBank - Punto no obligatorio en QBanks - crear pregunta

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/SubjectsDrawer.js
plugins/leemons-plugin-admin/frontend/src/pages/private/Setup/components/AddCenterDrawer.js
plugins/leemons-plugin-admin/frontend/src/pages/private/Setup/components/AddProfileDrawer.js
plugins/leemons-plugin-attendance-control/frontend/src/components/attendance-control-drawer.js
plugins/leemons-plugin-board-messages/frontend/src/components/DetailDrawer/DetailDrawer.js
plugins/leemons-plugin-calendar/frontend/src/components/CalendarEventModal/CalendarEventModal.js
plugins/leemons-plugin-calendar/frontend/src/components/EventDetailPanel/EventDetailPanel.js
plugins/leemons-plugin-calendar/frontend/src/components/calendar-simple-event-modal.js
plugins/leemons-plugin-comunica/frontend/src/components/ChatAddUsersDrawer/ChatAddUsersDrawer.js
plugins/leemons-plugin-comunica/frontend/src/components/ChatDrawer/ChatDrawer.js
plugins/leemons-plugin-comunica/frontend/src/components/ChatInfoDrawer/ChatInfoDrawer.js
plugins/leemons-plugin-comunica/frontend/src/components/ChatListDrawer/ChatListDrawer.js
plugins/leemons-plugin-comunica/frontend/src/components/ChatListDrawerIntermediate/ChatListDrawerIntermediate.js
plugins/leemons-plugin-dataset/frontend/src/components/_DatasetItemDrawer/DatasetItemDrawer.js
plugins/leemons-plugin-dataset/frontend/src/components/_DatasetItemDrawer/components/FieldConfigLocale/common/TranslateOptions.js
plugins/leemons-plugin-families/frontend/src/components/SearchUserDrawer/SearchUserDrawer.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/components/ConfigModal/ConfigModal.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetEmbedList.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetList.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetListDrawer.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/AssetPickerDrawer.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetSetup/PermissionsDataDrawer.js
plugins/leemons-plugin-multilanguage/frontend/src/components/TranslatorModal/TranslatorModal.js
plugins/leemons-plugin-users/frontend/src/components/UserDetailDrawer.js
plugins/leemons-plugin-users/frontend/src/components/UserModal/UserDetailModal.js

In order to release the name for a future improved and better component

Renamed all `Drawer`s to `BaseDrawer`

---

plugins/leemons-plugin-leebrary/frontend/src/components/LibraryCardBody/LibraryCardBody.js
plugins/leemons-plugin-tests/backend/core/questions-banks/listQuestionsBanks.js
plugins/leemons-plugin-tests/backend/core/questions-banks/saveQuestionsBanks.js

fix(tests): save published flag in QuestionBank model
fix(tests): listQuestionBanks returns only current versions
chore(leebrary): show Draft Badge in LibraryCard for Question Banks

List only last published Question Banks in test creation

---

plugins/leemons-plugin-menu-builder/frontend/src/components/mainMenu/index.js

fix(menu): be more consistent on menu platform name

Show change language menu item if it has multiple languages

---

plugins/leemons-plugin-academic-portfolio/backend/core/classes/updateClass.js

Ticket: [Notion](https://www.notion.so/leemons/Leemons-Product-Kanban-v2-0-b49859e964e145edb4e22caddb4571f7?p=b02da2c1564c456386bff42889ea43cf&pm=s)

Bug: Ajustes refactor Comunica v3

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/Selectors/SelectProgram.js
plugins/leemons-plugin-scores/backend/config/constants.js
plugins/leemons-plugin-scores/backend/i18n/es.js
plugins/leemons-plugin-scores/frontend/src/components/Weights/components/SubjectsWeightingTable/hooks/usePreparedData.js
plugins/leemons-plugin-scores/frontend/src/pages/WeightsPage.js
plugins/leemons-plugin-users/backend/core/profiles/createInitialProfiles/teacher.json

- **fix(scores): add permissions to weighting rules**
- **fix(scores): adapt to new academic-portfolio changes**

adapt score weights to new academic portfolio

---

plugins/leemons-plugin-grades/frontend/src/components/EvaluationDetail/components/Scales.js

fix(grades): can add "0" to numeric grade

Academic Rules - No permite poner nota “0” (cero) que es necesaria ("Blocker")

---

plugins/leemons-plugin-academic-portfolio/backend/i18n/en.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/es.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/ProgramSetupDrawer/AddProgramForm.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/ProgramSetupDrawer/CoursesSetup.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/ProgramSetupDrawer/UpdateProgramForm.js

- Hide component that shows credits when a program doesn't use credits (creation & update) 
- fix wrong translations 
- Hide auto-assignment option as is not implemented yet

AcaPortfolio fixes for Program Creaton

---

plugins/leemons-plugin-academic-portfolio/frontend/src/helpers/getClassData.js
plugins/leemons-plugin-academic-portfolio/frontend/src/hooks/useClassroomsData.js
plugins/leemons-plugin-assignables/frontend/src/helpers/getClassData.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetEmbedList.js
plugins/leemons-plugin-tasks/frontend/src/components/Correction/Correction.js

chore(tasks): trim end decimals and allow both commas and periods in correction

fix(assignables): do not throw if no subjectCredits

---

plugins/leemons-plugin-grades/frontend/src/components/EvaluationDetail/components/IsPercentage.js
plugins/leemons-plugin-grades/frontend/src/components/EvaluationDetail/components/MinScaleToPromote.js
plugins/leemons-plugin-grades/frontend/src/components/EvaluationDetail/components/Name.js
plugins/leemons-plugin-grades/frontend/src/components/EvaluationDetail/components/OtherTags.js
plugins/leemons-plugin-grades/frontend/src/components/EvaluationDetail/components/Scales.js
plugins/leemons-plugin-grades/frontend/src/components/EvaluationDetail/components/Type.js
plugins/leemons-plugin-grades/frontend/src/components/EvaluationDetail/index.js
plugins/leemons-plugin-grades/frontend/src/pages/private/Evaluations/EvaluationList.js

fix(grades): Evaluation system - If a ES is in use, show drawer with all inputs and data on readonly/disabled mode.

Sistemas de Evaluación - Deshabilitar borrado de SE si está en uso (edición)

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetForm/AssetForm.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/components/DetailContent.js

fix(tests): add three rows to text areas

Test creation - Ajustes

---

plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/ContentData.js
plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/EvaluationData.js
plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/InstructionData.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/Edit.js

fix(test): change logic of buttons if test creation have Evaluation step.
fix(task): fix stage height

Task - Creation - Revisar que el stage llegue hasta el footer

---

plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/Instructions/Instructions.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/OtherOptions/OtherOptions.js
plugins/leemons-plugin-board-messages/frontend/src/components/DetailDrawer/DetailDrawer.js
plugins/leemons-plugin-common/frontend/src/tags/TagsAutocomplete.js
plugins/leemons-plugin-curriculum/frontend/src/components/FormTheme/CurriculumGroupItem.js
plugins/leemons-plugin-curriculum/frontend/src/components/FormTheme/CurriculumListSubItems.js
plugins/leemons-plugin-curriculum/frontend/src/components/FormTheme/CurriculumWysiwyg.js
plugins/leemons-plugin-curriculum/frontend/src/components/FormTheme/WysiwygWidget.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/Detail/components/DetailQuestionForm.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/Detail/components/DetailQuestions.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/Detail/components/QuestionForm.js
plugins/leemons-plugin-tasks/frontend/src/components/Correction/Correction.js
plugins/leemons-plugin-tasks/frontend/src/components/Correction/__DEPRECATED__components/Accordion.js
plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/ContentData.js
plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/InstructionData.js
plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/components/Development/Development.js
plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/components/SelfReflection/SelfReflection.js
plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/components/Submissions/Submissions.js
plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/components/DetailQuestionForm.js
plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/components/QuestionForm.js
plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/components/question-types/Map/index.js
plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/components/question-types/MonoResponse/index.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/Result.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/components/DetailInstructions.js

fix(plugins): Fix TextArea and TextInputEditors height.

Assets - Creation - Assignments - Alto de los text area erróneo

---

plugins/leemons-plugin-scores/backend/core/scores/setScores.js
plugins/leemons-plugin-scores/backend/i18n/en.js
plugins/leemons-plugin-scores/backend/i18n/es.js
plugins/leemons-plugin-scores/frontend/package.json
plugins/leemons-plugin-scores/frontend/src/components/EvaluationNotebook/EvaluationNotebook.js
plugins/leemons-plugin-scores/frontend/src/components/EvaluationNotebook/ScoresTable/ScoresTable.js
plugins/leemons-plugin-scores/frontend/src/components/EvaluationNotebook/ScoresTable/hooks/useActivities.js
plugins/leemons-plugin-scores/frontend/src/components/EvaluationNotebook/ScoresTable/hooks/useStudents.js
plugins/leemons-plugin-scores/frontend/src/components/EvaluationNotebook/components/NotebookFilters/NotebookFilters.js
plugins/leemons-plugin-scores/frontend/src/components/EvaluationNotebook/components/NotebookFilters/hooks/useOnChange.js
plugins/leemons-plugin-scores/frontend/src/components/EvaluationNotebook/components/PageFooter/PageFooter.js
plugins/leemons-plugin-scores/frontend/src/components/EvaluationNotebook/components/PageFooter/hooks/useCloseEvaluation.js
plugins/leemons-plugin-scores/frontend/src/components/EvaluationNotebook/components/PageFooter/hooks/useDownloadScoreReport.js
plugins/leemons-plugin-scores/frontend/src/components/FinalEvaluationNotebook/FinalEvaluationNotebook.js
plugins/leemons-plugin-scores/frontend/src/components/FinalEvaluationNotebook/components/Filters.js
plugins/leemons-plugin-scores/frontend/src/components/FinalEvaluationNotebook/hooks/useStudents.js
plugins/leemons-plugin-scores/frontend/src/components/FinalEvaluationNotebook/hooks/useTableData.js
plugins/leemons-plugin-scores/frontend/src/components/FinalNotebook/FinalScores.js
plugins/leemons-plugin-scores/frontend/src/components/MyScores/components/SubjectsScoreList/components/SubjectScoreColumn/components/ActivityScoreDisplay/ActivityScoreDisplay.js
plugins/leemons-plugin-scores/frontend/src/components/MyScores/components/SubjectsScoreList/components/SubjectScoreColumn/components/ActivityScoreTotal/ActivityScoreTotal.js
plugins/leemons-plugin-scores/frontend/src/components/MyScores/components/SubjectsScoreList/components/SubjectScoreColumn/hooks/useActivities.js
plugins/leemons-plugin-scores/frontend/src/components/ScoresPage/Filters/Filters.js
plugins/leemons-plugin-scores/frontend/src/components/ScoresPage/Filters/hooks/useSelectedPeriod.js
plugins/leemons-plugin-scores/frontend/src/components/Tables/ScoresBasicTable/ActivityHeader/ActivityHeader.js
plugins/leemons-plugin-scores/frontend/src/components/Tables/ScoresBasicTable/ScoresBasicTable.js
plugins/leemons-plugin-scores/frontend/src/components/Weights/components/WeightConfigDrawer/components/SelectType.js
plugins/leemons-plugin-scores/frontend/src/pages/EvaluationNotebookPage.js
plugins/leemons-plugin-scores/frontend/src/requests/scores/setScores.js
plugins/leemons-plugin-scores/frontend/src/stores/evaluationNotebookStore.js
yarn.lock

- **chore(scores): disable modules weighting type**
- **feat(scores): add final evaluation view to teachers**
- **feat(scores): evaluation notebook final period**
- **fix(scores): fixed wrong average score calculations**

Scores - Final evaluation view 

---

plugins/leemons-plugin-academic-calendar/frontend/src/pages/private/program/index.js
plugins/leemons-plugin-academic-calendar/frontend/src/pages/private/regional/index.js
plugins/leemons-plugin-grades/frontend/src/pages/private/Evaluations/EvaluationList.js

- **fix(grades): add optional chaining to "inUse" new property**
- **fix(academic-calendar): reload program and regional calendar when view changes (click on sidemenu items)**

fix(grades): add optional chaining to "inUse" new property

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetEmbedList.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPlayer/AssetPlayer.js

fix(AssetEmbedList): Change drawer width to the same of LibraryDetailDrawer
fix(AssetPlayer): keep the same image on Drawer when user click on Zoom button

Modulos - Execution - Drawer de recursos 

---

plugins/leemons-plugin-academic-calendar/frontend/src/pages/private/regional/components/regionalConfigDetail.js

fix(academic-calendar): implement add method on renderActionButton property on TableInput components on create regional calendar drawer

Regional Calendar - No se pueden agregar eventos

---

plugins/leemons-plugin-academic-calendar/frontend/src/pages/private/regional/components/regionalConfigDetail.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPlayerWrapper.js

fix(protected-library-player-page): fix scroll with PDF

Assets - Execution - PDF - No funciona el scroll 

---

plugins/leemons-plugin-academic-portfolio/backend/services/rest/programs.rest.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/ProgramSetupDrawer/UpdateProgramForm.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/ProgramsDetailTable.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/common/ReadOnlyField.js
plugins/leemons-plugin-academic-portfolio/frontend/src/hooks/useProgramDetail.js
plugins/leemons-plugin-academic-portfolio/frontend/src/pages/private/programs/ProgramsPage.js

Programs Page
- Show Evaluation system in Program drawer
- Show loader when duplicating
- Show loader when archiving
- Move to archive tab after archiving a program

Issue/aca portfolio 164: Programs Page fixes

---

plugins/leemons-plugin-scores/backend/i18n/en.js
plugins/leemons-plugin-scores/backend/i18n/es.js
plugins/leemons-plugin-scores/frontend/src/components/EvaluationNotebook/ScoresTable/ScoresTable.js
plugins/leemons-plugin-scores/frontend/src/components/Tables/ScoresBasicTable/ScoreCell/ScoreCell.js
plugins/leemons-plugin-scores/frontend/src/components/Tables/ScoresBasicTable/ScoreCell/ScoreCell.styles.js
plugins/leemons-plugin-scores/frontend/src/components/Tables/ScoresBasicTable/ScoresBasicTable.js

clean table by removing unnecessary `not evaluated`

styles(scores): re-styled `ScoresBasicTable`

---

plugins/leemons-plugin-menu-builder/frontend/src/components/MainNavBar/components/UserButton/UserButton.js
plugins/leemons-plugin-users/backend/i18n/en.js
plugins/leemons-plugin-users/backend/i18n/es.js
plugins/leemons-plugin-users/frontend/Private.js
plugins/leemons-plugin-users/frontend/src/components/UserDetail/UserDetail.js
plugins/leemons-plugin-users/frontend/src/components/UserDetailDrawer.js
plugins/leemons-plugin-users/frontend/src/components/UserForm.js
plugins/leemons-plugin-users/frontend/src/pages/private/users/DetailUser/UserInfo.js
plugins/leemons-plugin-users/frontend/src/request/updateUserImage.js

New `UserInfo` page and integrate real-time avatar updates via MQTT
- Add the new user info detail page.
- Implement real-time avatar updates in UserButton component using SocketIoService.
- Add state management for avatar URL to handle updates.
- Adjust Avatar component props to use new avatar state.

feat(users): Add new `UserInfo`

---

plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardFooter/DashboardCardFooter.js
plugins/leemons-plugin-leebrary/frontend/src/pages/private/assignables/Correction.js
plugins/leemons-plugin-tasks/frontend/src/components/Correction/Correction.js
plugins/leemons-plugin-tasks/frontend/src/components/StudentCorrection/StudentCorrection.js

fix(leebrary): do not hide footer if fromExecution is removed from URL

Do not hide footer in correction if fromExeuction is removed form URL

---

plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardFooter/DashboardCardFooter.js
plugins/leemons-plugin-tasks/frontend/src/components/Correction/Correction.js

fix(tasks): use minScale as default value in Correction form

fix(learning-paths): only show evaluate button in dashboard if some student is not evaluated

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/SubjectPicker/SubjectPicker.js
plugins/leemons-plugin-assignables/backend/i18n/en.js
plugins/leemons-plugin-assignables/backend/i18n/es.js

feat(assignables): prompt the user to change the program and delete current selection

feat(assignables): change session program to assignment program

---

plugins/leemons-plugin-academic-portfolio/frontend/src/hooks/academicProfiles/useIsAcademicProfile.js
plugins/leemons-plugin-dashboard/frontend/src/pages/private/Dashboard/index.js
plugins/leemons-plugin-users/frontend/src/hooks/useUserProfile.js

refactor(dashboard): use admin profile to determine which dashboard to use

fix(users): pick current userProfile from sessionProfile instead of localStorage

---

plugins/leemons-plugin-leebrary/backend/i18n/en.js
plugins/leemons-plugin-leebrary/backend/i18n/es.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPlayer/components/ProgressBar/ProgressBar.styles.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryCardCC/LibraryCardCC.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryCardCC/LibraryCardCC.styles.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryTool/AssetPlayerWrapperExecution/AssetPlayerWrapperExecution.js
plugins/leemons-plugin-leebrary/frontend/src/pages/private/assignables/Execution.js
yarn.lock

fix(AssetPlayers):
- Broken height on PDF execution fixed.
- Cursor pointer on LibraryCard CC when hover 
- Instructions accordion label on Student execution.
- LibraryCard CC on execution, at top left on the stage container. 
- zIndex on video player controls, when the video has vertical scroll.

Players Ejecución - Ajustes Vol I

---

plugins/leemons-plugin-leebrary/frontend/src/components/LibraryTool/LibraryBubbleMenu.js

fix(LibraryBubbleMenu): in CCreator, if add an asset type bookmark and is a youtube link, can see "player option" in bubble menu

Recuperar Player en assets de tipo Bookmark (youtube) para CCreator

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/SubjectSetupDrawer/ReferenceGroupsClassroomsSetup.js
plugins/leemons-plugin-academic-portfolio/frontend/src/helpers/getSubjectGroupCourseNamesFromClassData.js
plugins/leemons-plugin-academic-portfolio/frontend/src/widgets/user-classes-swiper/index.js
plugins/leemons-plugin-dashboard/frontend/src/pages/private/ClassDashboard/index.js

fix(academic-portfolio): create new helper to format subject, course and group. Add this new helper to subjects carrousel in dashboards and header dropdown in subject dashboard

Transversal - Control de alias de Aula (grupo de alumnos) en varios frontales y cursos para programas tipo MOOC 

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/AcademicTree/NodeRenderer/NodeRenderer.styles.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryDetailContent/LibraryDetailContent.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryDetailContent/LibraryDetailContent.styles.js

fix(tokens): change hardcoded colors for tokens.

Añadir tokens de color 

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetList.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryCardFooter/LibraryCardFooter.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryCardFooter/LibraryCardFooter.styles.js

fix(leebrary): add color to mediaType selector elements (icons) on AssetList header

Main Library - Ajustes de maquetación

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetForm/AssetForm.js

Handle editing cases when setting the cover/name of the asset form in AssetForm

fix(leebrary): Media file asset edition.

---

plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/components/Config/Config.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleSetup/components/Resources/components/ResourcesTable/ResourcesTable.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleSetup/components/StructureData/components/AvatarActivity/AvatarActivity.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleSetup/components/StructureData/components/AvatarActivity/AvatarActivity.styles.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleSetup/components/StructureData/components/ModuleComposer/ModuleComposer.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleSetup/components/StructureData/components/ModuleComposer/components/ResourceRenderer/ResourceRenderer.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetEmbedList.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/components/AssetList/components/RowList/Item.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/components/AssetList/components/RowList/List.js
plugins/leemons-plugin-leebrary/frontend/src/components/Attachments/Attachments.js
plugins/leemons-plugin-leebrary/frontend/src/components/Attachments/Attachments.styles.js
plugins/leemons-plugin-leebrary/frontend/src/components/Attachments/AttchmentItem.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryCard/LibraryCard.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryCardEmbed/LibraryCardEmbed.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryCardEmbed/LibraryCardEmbed.styles.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryDetailContent/LibraryDetailContent.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryTool/LibraryPlayer.js
plugins/leemons-plugin-tasks/backend/i18n/en.js
plugins/leemons-plugin-tasks/backend/i18n/es.js
plugins/leemons-plugin-tasks/frontend/src/components/Student/TaskDetail/components/IntroductionStep/IntroductionStep.js
plugins/leemons-plugin-tasks/frontend/src/pages/private/library/TaskSetupPage.js

feat(LibraryCardEmbedded): 
- Module execution and assignation
- Task creation and execution
- Test creation and execution

New Asset Players - Nivel 2, 2.5 - C.Creator & assignment execution Vol.2

---

plugins/leemons-plugin-tests/backend/i18n/es.js

fix(tests):Change text variable only spanish language  for the question bank creation.

QBank - Creation - Texto de ayuda en listado de respuestas erróneo.

---

plugins/leemons-plugin-leebrary-aws-s3/backend/core/provider/getReadStream.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/StudentInstance/components/Question.js

fix(leebrary): resources can download directly with the download button on LibraryDetailToolbar => handleOnDownload function.

Descarga de PDF desde el drawer

---

plugins/leemons-plugin-tests/frontend/src/pages/private/tests/StudentInstance/components/Question.js

fix(tests): on execution, if user click on one response, prevent move…ment of progress bar if bottom right button chages his copy.

Salto posición botón footer test

---

plugins/leemons-plugin-leebrary/frontend/src/components/LibraryCardEmbed/LibraryCardEmbed.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryTool/LibraryPlayer.js

fix(leebrary): change logic to show icons on LibraryCardEmbed (minicards) in CCreator.

Players - Minicard de marcador del C. Creator, cambiar el icono de descarga por el de enlace externo

---

plugins/leemons-plugin-content-creator/frontend/src/pages/View/index.js
plugins/leemons-plugin-tasks/backend/i18n/en.js
plugins/leemons-plugin-tasks/backend/i18n/es.js
plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/components/Submissions/components/File/File.js

fix(tasks): Creation. Add label to button in tags input (file format tags).

Creation - Task - Añadir label de añadir

---

plugins/leemons-plugin-scores/frontend/src/components/MyScores/components/PageFooter/hooks/useDownloadStudentReport.js

fix(scores): assume the activity is submitted if it has an score in the student report

fix(scores): provide activity id to downloadStudentReport

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/ProgramBarSelector/ProgramBarSelector.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/Selectors/SelectProgram.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/SubjectPicker/SubjectPicker.js
plugins/leemons-plugin-academic-portfolio/frontend/src/pages/private/AcademicTreePage.js
plugins/leemons-plugin-academic-portfolio/frontend/src/pages/private/subjects/SubjectsPage.js
plugins/leemons-plugin-attendance-control/backend/i18n/en.js
plugins/leemons-plugin-attendance-control/backend/i18n/es.js
plugins/leemons-plugin-attendance-control/frontend/src/pages/private/Assistance.js
plugins/leemons-plugin-calendar/frontend/src/components/KanbanFilters/KanbanFilters.js
plugins/leemons-plugin-curriculum/frontend/src/pages/private/AddCurriculumStep0/index.js
plugins/leemons-plugin-dashboard/frontend/src/pages/private/ClassDashboard/index.js
plugins/leemons-plugin-scores/frontend/src/components/PeriodList/PeriodList.js
plugins/leemons-plugin-scores/frontend/src/components/PeriodSelector/PeriodSelector.js
plugins/leemons-plugin-scores/frontend/src/components/ScoresPeriodForm/ScoresPeriodForm.constants.js
plugins/leemons-plugin-scores/frontend/src/components/ScoresPeriodForm/ScoresPeriodForm.js
plugins/leemons-plugin-scores/frontend/src/components/__DEPRECATED__/ReviewerPage/Filters.js

fix(transversal): Order Selects data for programs, subjects and groups.
- Select de programas en main dashboard   ☑️
- Select de asignaturas en SubjectDashboard ☑️
- Select de programa en Main Ongoing  ☑️
- Select de programa en calendar/kanban ☑️
- Select de programa en todas las interfacez de scores ☑️
- Select de programa/asignatura dentro de la creación o asignación de assets ☑️
- Todos los select de programa/asignatura de las pantallas de admin ☑️

Orden en los dropdowns de programas y asignaturas

---

plugins/leemons-plugin-academic-calendar/frontend/src/pages/private/regional/index.js

Prepare the correct payload in frontend before making the create/update request to the backend.

Fix regional calendar update request in frontend

---

plugins/leemons-plugin-content-creator/backend/i18n/en.js
plugins/leemons-plugin-content-creator/backend/i18n/es.js
plugins/leemons-plugin-learning-paths/backend/i18n/en.js
plugins/leemons-plugin-learning-paths/backend/i18n/es.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleSetup/components/Resources/Resources.js

fix(content-creator): removed unused localization

fix(lModules): changed label from publish options to finish

---

plugins/leemons-plugin-assignables/frontend/src/components/Assignment/FormComponent.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/ActivityDatesPicker.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/Container/Container.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/EvaluationType/EvaluationType.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/GroupPicker/GroupPicker.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/Instructions/Instructions.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/Presentation/Presentation.js

fix(assignation): add space between sections.

Total Layout creation Form - Error en GAP entre “secciones”

---

plugins/leemons-plugin-calendar/frontend/src/helpers/getCalendarNameWithConfigAndSession.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetSetup/PermissionsData.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryDetailContent/components/MetadataDisplay/MetadataDisplay.js

fix(calendar): parse calendar.name correctly if calendar is user calendar
fix(leebrary): delete Dimensions if asset is audio type. Add dependecies array to useMemo in Permissions data.

Unificar posición de Nombre y Apellidos y controlar espaciados

---

plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/StudentInstance/components/QuestionsStep.js

fix(feedback): add optional chaining to prevent error and blank page.

Blancazo en segundo paso ejecución encuestas

---

plugins/leemons-plugin-leebrary/frontend/src/components/LibraryTool/LibraryExtension.js

fix(CCreator): can download rar file from document.

C.Creator - Vista previa/ejecución - No se descarga asset tipo “file/application”

---

plugins/leemons-plugin-calendar/frontend/src/pages/private/Calendar/index.js

Add subject icon if event is type task and have and icon. If no icon, show initials of current subject.

Calendario - Icono y colores del evento

---

plugins/leemons-plugin-feedback/backend/i18n/en.js
plugins/leemons-plugin-feedback/backend/i18n/es.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/Detail/components/SelectResponse/components/ListInputRender.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/Detail/components/SelectResponse/index.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/StudentInstance/components/LikertResponse/LikertResponse.styles.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/StudentInstance/components/LikertResponse/index.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/StudentInstance/components/NetPromoterScoreResponse/NetPromoterScoreResponse.styles.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/StudentInstance/components/NetPromoterScoreResponse/index.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/StudentInstance/components/questions/SelectResponseQuestion.js

fix(feedback): add hover and selected styles in all questions.
fix(feedback): add text variables to ListItem and fix buttons

Token no cambiado en Encuestas y Score

---

plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/components/question-types/MonoResponse/components/ListInputRender.js
plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/components/question-types/MonoResponse/index.js

fix(questionBank): fix button problems and add onKeyDown to save question

QB - Botones de guardar respuesta

---

plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/ModuleDashboard.js
plugins/leemons-plugin-tasks/frontend/src/components/StudentCorrection/StudentCorrection.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/Result.js

fix(LModules): Set gradesViewed timestamp if al gradable sub-activities has all grades

fix(assignables): Do not set gradesViewed timestamp if it's module sub-activity

---

plugins/leemons-plugin-calendar/frontend/src/components/CalendarEventModal/CalendarEventModal.js
plugins/leemons-plugin-calendar/frontend/src/components/calendar-event-modal.js

- Added EditWriteIcon and DeleteBinIcon to CalendarEventModal for edit and delete actions.
- Integrated openDeleteConfirmationModal for event deletion confirmation.
- Refactored imports for better organization and readability.

feat(calendar): add edit and delete actions to CalendarEventModal

---

plugins/leemons-plugin-assignables/backend/i18n/en.js
plugins/leemons-plugin-assignables/backend/i18n/es.js
plugins/leemons-plugin-dashboard/frontend/src/components/WelcomeWidget/components/EmptyState/EmptyState.js
plugins/leemons-plugin-leebrary/backend/i18n/en.js
plugins/leemons-plugin-leebrary/backend/i18n/es.js
plugins/leemons-plugin-leebrary/frontend/src/components/ListEmpty/ListEmpty.js

fix(dashboard): localize links to public web.
fix(leebrary): localize links on empty states.

fix: use EmptyStates and Welcome links based on user locale

---

plugins/leemons-plugin-assignables/backend/core/instances/getInstancesStatus/getInstancesStatus.js
plugins/leemons-plugin-assignables/backend/core/instances/getInstancesStatus/getStatus.unit.test.js
plugins/leemons-plugin-assignables/backend/core/instances/getInstancesStatus/getStatusForStudent.js
plugins/leemons-plugin-assignables/backend/core/instances/getInstancesStatus/getStatusForTeacher.js
plugins/leemons-plugin-calendar/backend/core/calendar/getCalendarsToFrontend.js
plugins/leemons-plugin-calendar/frontend/src/components/KanbanTaskCard/KanbanTaskCard.js

- **feat(assignables): Added status handling for teacher instances**
- **feat(assignables): calculate based on actual subjects count**

feat(assignables): Added status handling for teacher instances

---

plugins/leemons-plugin-feedback/backend/i18n/en.js
plugins/leemons-plugin-feedback/backend/i18n/es.js

fix(feedback): remove "More info about NPS" from Alert component.

fix(feedback): remove "More info about NPS" from Alert component

---

plugins/leemons-plugin-assignables/backend/core/assignations/getAssignations/getModuleActivitesTimestampsAndGrades.js
plugins/leemons-plugin-assignables/frontend/src/components/EvaluationCard/EvaluationCardRightElement/EvaluationCardRightElement.js
plugins/leemons-plugin-assignables/frontend/src/components/Ongoing/AssignmentList/components/ActivitiesList/ActivitiesList.js
plugins/leemons-plugin-assignables/frontend/src/hooks/assignableInstance/usePendingEvaluationsCount.js
plugins/leemons-plugin-tasks/frontend/src/hooks/student/useStudentAssignationMutation.js
yarn.lock

fix(assignables): Remove slash and total module activities from NYA Teacher card.

fix(assignables): Remove total module activities from teacher's NYA card

---

plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleSetup/components/StructureData/components/ModuleComposer/components/ResourceRenderer/ResourceRenderer.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryCardEmbed/LibraryCardEmbed.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryCardEmbed/LibraryCardEmbed.styles.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryDetailContent/components/DetailContent/DetailContent.js

- LibraryCardEmbed: some strings can't clamp correctly and overflow the card.
- LibraryDetail: TextClamp on title (1 line) and description (2 lines)

fix(leebrary): Added `TextClamp` to `LibraryDetail`

---

plugins/leemons-plugin-tasks/frontend/src/components/TaskSetupPage/components/Submissions/components/File/File.js

fix(task): add in case of rtf files, the file extension not mime value.

fix(tasks): Handled `.rtf` file extension individually

---

plugins/leemons-plugin-assignables/backend/core/assignations/getAssignations/getModuleActivitesTimestampsAndGrades.js
plugins/leemons-plugin-assignables/frontend/src/hooks/assignableInstance/usePendingEvaluationsCount.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/components/NewResource.js

fix(leebrary): AssetPickerDrawer accept all filetypes on FileUpload component.

fix(leebrary): Accept any file type in AssetPickerDrawer

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/EnrollUserSummary/EnrollUserSummary.js

fix(academic-portfolio): on EnrollUserSummary, delete conditional and set 'enrollments' text variable for all cases

fix(academic-portfolio): on `EnrollUserSummary` use "enrollments" copy

---

plugins/leemons-plugin-tests/frontend/src/pages/private/tests/Result.js

fix(tests): TextClamp (2 lines) in table resutl. Question description.

fix(tests): TextClamp (2 lines) in table result. Question description

---

plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/Preview/index.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/StudentInstance/components/QuestionsCard.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/StudentInstance/components/questions/QuestionTitle.js

fix(feedback): User can navigate between questions on preview mode

fix(feedback): User can navigate between questions on preview mode

---

plugins/leemons-plugin-learning-paths/backend/i18n/en.js
plugins/leemons-plugin-learning-paths/backend/i18n/es.js
plugins/leemons-plugin-learning-paths/frontend/src/widgets/leebrary/Detail.js
plugins/leemons-plugin-learning-paths/frontend/src/widgets/leebrary/ListCard.js

Signed-off-by: Miguel Ángel Florido Cifuentes <miguel@leemons.io>

fix(LPaths): Added localizations for delete and duplication in leebrary

---

plugins/leemons-plugin-users/frontend/src/components/SelectUserAgent.js

…t to filter correctly users by profile

fix(users): Remove onlyForTeachers flag from SelectUserAgent component

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetForm/AssetForm.js

fix(leebrary): Remove subititle on AssetForm

fix(leebrary): Remove subititle on AssetForm

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetSetup/PermissionsData.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetSetup/components/PermissionsDataUsers.js
plugins/leemons-plugin-users/frontend/src/components/SelectUserAgent.js

fix(leebrary-users): Refactor for handle share assets in leebrary, not in users plugins

fix(leebrary): Refactor to handle share assets in leebrary not users

---

plugins/leemons-plugin-menu-builder/backend/i18n/en.js
plugins/leemons-plugin-menu-builder/backend/i18n/es.js

fix(menu-builder): Change text variable value.

fix(menu-builder): Change text variable value

---

plugins/leemons-plugin-tasks/frontend/src/components/Student/TaskDetail/components/SubmissionStep/components/File/File.js

fix(task): if file is rft, add all accept cases

fix(task): if file is rft, add all accept cases

---

plugins/leemons-plugin-assignables/backend/i18n/en.js
plugins/leemons-plugin-assignables/backend/i18n/es.js
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/ActivityHeader.constants.js
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/index.js
plugins/leemons-plugin-tasks/frontend/src/components/Student/TaskDetail/TaskDetail.js
plugins/leemons-plugin-tasks/frontend/src/components/Student/TaskDetail/components/SubmissionStep/SubmissionStep.js

fix(tasks): On module preview, change "go back to dashboard" button to Header.

fix(tasks): On module preview, change "go back to dashboard" button

---

plugins/leemons-plugin-academic-portfolio/frontend/src/helpers/getSubjectGroupCourseNamesFromClassData.js
plugins/leemons-plugin-academic-portfolio/frontend/src/widgets/user-classes-swiper/index.js
plugins/leemons-plugin-assignables/frontend/src/components/NYACard/NYACard.styles.js
plugins/leemons-plugin-assignables/frontend/src/widgets/dashboard/nya/components/ActivityCarousel.js
plugins/leemons-plugin-assignables/frontend/src/widgets/dashboard/nya/components/EvaluationsCarousel.js
plugins/leemons-plugin-dashboard/frontend/src/pages/private/ClassDashboard/index.js

New subject carousel on student/teacher dashboard.

fix(dashboard): Refactor subjects carousel and review all Swipers

---

plugins/leemons-plugin-tests/frontend/src/components/QuestionImageMarkersModal.js

fix(tests: QuestionBanks): Truncate text on marker contextual menu. Add tooltip when text is truncated.

QB - Pregunta tipo Mapa: menu contextual truncado

---

plugins/leemons-plugin-academic-portfolio/backend/i18n/en.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/es.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/EnrollUserSummary/EnrollUserSummary.js
plugins/leemons-plugin-users/frontend/src/pages/private/users/DetailUser/UserInfo.js

- Change text if user is student to "Enrollments" and if is teacher, to "Classes". If teacher is in user detail section, hide "Docent" column header and values.

Literales perfil profesor

---

plugins/leemons-plugin-tests/frontend/src/components/QuestionImageMarkersModal.js

fix(tests): on question bank creation, on a map question type, fix marker contextual menu when marker is on right margin of the photo.

♻️ QB - Pregunta tipo Mapa: menu contextual truncado

---

plugins/leemons-plugin-tests/backend/i18n/en.js
plugins/leemons-plugin-tests/backend/i18n/es.js
plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/components/DetailQuestionForm.js
plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/components/question-types/Map/index.js
plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/components/question-types/MonoResponse/index.js

feat(question-banks): Remove headings on TextEditorInput header for "Statement" and "Feedback"  when user create new questions

WYSIWYG Erróneo en Question Banks

---

plugins/leemons-plugin-academic-portfolio/backend/core/classes/updateClass.js
plugins/leemons-plugin-academic-portfolio/frontend/src/widgets/class-detail/index.js
plugins/leemons-plugin-academic-portfolio/frontend/src/widgets/class-students/index.js
plugins/leemons-plugin-assignables/backend/i18n/en.js
plugins/leemons-plugin-assignables/backend/i18n/es.js
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/components/ChatDisplay/ChatDisplay.js
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/components/CloseButtons/CloseButtons.js
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/index.js
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/index.style.js
plugins/leemons-plugin-assignables/frontend/src/components/NYACard/NYACard.js
plugins/leemons-plugin-comunica/frontend/src/components/RoomAvatar/RoomAvatar.js
plugins/leemons-plugin-dashboard/frontend/src/pages/private/ClassDashboard/ClassDashboard.styles.js
plugins/leemons-plugin-dashboard/frontend/src/pages/private/ClassDashboard/index.js
plugins/leemons-plugin-tasks/frontend/src/components/Correction/Correction.js
plugins/leemons-plugin-tasks/frontend/src/components/StudentCorrection/StudentCorrection.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/Result.js
plugins/leemons-plugin-users/backend/i18n/en.js
plugins/leemons-plugin-users/backend/i18n/es.js
plugins/leemons-plugin-users/frontend/globalContext.js
plugins/leemons-plugin-users/frontend/src/components/UserDetail/UserDetail.js
plugins/leemons-plugin-users/frontend/src/components/UserDetailDrawer.js
plugins/leemons-plugin-users/frontend/src/session.js

- Updated `RoomAvatar.js` in `leemons-plugin-comunica` to handle image changes and attached icons.
- Modified `globalContext.js` in `leemons-plugin-users` to include a description, button, and modal for updating the dataset.

Epic Comunica: ChatHub controller

---

plugins/leemons-plugin-deployment-manager/backend/core/deployments/addPluginsToDeployment.js

fix:(deployment-manager): Only create relations between desired plugins

---

plugins/leemons-plugin-assignables/frontend/src/components/Details/Details.js

fix(assignables): reduce gap between graph and table.

fix(assignables): reduce gap between graph and table

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/ProgramSetupDrawer/AddProgramForm.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/ProgramSetupDrawer/UpdateProgramForm.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/SubjectSetupDrawer/SubjectForm.js
plugins/leemons-plugin-admin/frontend/src/pages/private/Setup/components/Organization.js
plugins/leemons-plugin-calendar/frontend/src/components/CalendarNewEventModal/CalendarNewEventModal.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryForm/LibraryDrawerForm.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryForm/LibraryForm.js

remove all useHsl properties in ColorPicker components.

fix: Remove useHsl prop in all color pickers in plugins

---

plugins/leemons-plugin-assignables/backend/config/constants.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/FormComponent.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/ActivityDatesPicker.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/components/HideFromCalendar.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/components/MaxTimeToggle.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/components/PeriodPicker/ControlledPeriodPicker.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/components/PeriodPicker/PeriodPicker.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/components/PeriodPicker/index.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/components/widgets/AlwaysAvailable.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/components/widgets/Fixed.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/context/ActivityDatesPickerProvider.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/hooks/useDatesPickerOptions/helpers/dynamicImport.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/hooks/useDatesPickerOptions/hooks/useWidgetLocalizations.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/hooks/useDatesPickerOptions/hooks/useWidgets.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/hooks/useDatesPickerOptions/index.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/hooks/useDatesPickerOptions/useDatesPickerOptions.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/ActivityDatesPicker/index.js

- **fix(academic-portfolio): SelectClass class values must have an unique value, otherwise is not possible to differentiate classes that belong to the same subject + adapt validation logic to allow removal of optional classroom id and alias set by the user**
- **feat(leebrary): WIP - Implement create/edit/view pages for new types of assets: recordings**
- **feat(academic-portfolio/leebrary/users): WIP - changes to integrate sessions plugin**
- **refactor(datasets): Convert wrapper and Title to ContextContainer**
- **feat(academic-portfolio): Normalize behavior between Subject and Class Selects**
- **feat(academic-portfolio): Add public class data endpoint**
- **feat(academic-portfolio+leebrary): Add sessions provider functionality to Academic portfolio + add new parameter to …

feat(assignables): Added widget system to assignmente datepicking option

---

plugins/leemons-plugin-academic-portfolio/backend/config/constants.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/en.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/es.js
plugins/leemons-plugin-academic-portfolio/frontend/src/pages/private/Blocks/index.js

- Changed block order from 4 to 8 in constants.js
- Added success message for saving blocks in English and Spanish translation files
- Enhanced Blocks component to include save functionality and updated layout

feat(blocks): update block order and add save alert

---

packages/leemons-deployment-manager/src/types.d.ts
plugins/leemons-plugin-users/backend/core/user-agents/searchUserAgents.js
plugins/leemons-plugin-users/frontend/src/hooks/index.js
plugins/leemons-plugin-users/frontend/src/hooks/useIsSuperAdmin.js
plugins/leemons-plugin-users/frontend/src/pages/private/users/ListUsers/index.js

- Added `useIsSuperAdmin` hook to check if the user is a super admin.
- Updated `searchUserAgents` function to include email search functionality.
- Modified `ListUsers` component to conditionally show all profiles based on super admin status.
- Updated `types.d.ts` to include user email in `UserAgent` interface.

feat(users): add super admin check and email search functionality

---

plugins/leemons-plugin-dataset/frontend/src/components/DatasetTable/DatasetTable.js

- Refactor `toggleModal` to accept item parameter directly
- Remove unused `itemToRemove` state
- Update `removeItem` function to pass item to `toggleModal`
- Add error logging for item removal

fix(dataset): resolve issue with item removal in DatasetTable

---

plugins/leemons-plugin-users/frontend/src/pages/private/users/ListUsers/index.js

- **fix(users): resolve page count on frontend.**
- **fix(users): substract 1 to the currentPage in the Pager**

fix(users): adjust Pager to avoid ending in the wrong or blank page

---

plugins/leemons-plugin-users/frontend/src/components/UserAdminDrawer/UserAdminDrawer.js
plugins/leemons-plugin-users/frontend/src/components/UserForm.js
plugins/leemons-plugin-users/frontend/src/pages/private/users/ListUsers/index.js

- feat(UserForm): trim and lowercase email inputs
- fix(ListUsers): update search query logic

fix(users): improve email handling and search functionality

---

plugins/leemons-plugin-academic-portfolio/backend/core/classes/classByIds.js
plugins/leemons-plugin-academic-portfolio/backend/core/classes/listSessionClasses.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/en.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/es.js
plugins/leemons-plugin-academic-portfolio/backend/models/program-subjects-credits.js
plugins/leemons-plugin-academic-portfolio/backend/validations/forms.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/SubjectSetupDrawer/SubjectForm.js

…ic and have no length restrictions (beyond the input length restriction of 256 characters)

feat(academic-portfolio): Allow subject internal ids to be alphanumeric

---

jsconfig.json
plugins/leemons-plugin-academic-portfolio/frontend/src/components/ClassroomItemDisplay/ClassroomItemDisplay.js
plugins/leemons-plugin-calendar/frontend/src/widgets/user-program-calendar/index.js
plugins/leemons-plugin-dashboard/frontend/src/components/AcademicDashboard/index.js
plugins/leemons-plugin-menu-builder/frontend/src/components/MainNavBar/MainNavBar.js
plugins/leemons-plugin-menu-builder/frontend/src/components/MainNavBar/components/UserButton/UserButton.constants.js
plugins/leemons-plugin-menu-builder/frontend/src/components/MainNavBar/components/UserButton/UserButton.js
plugins/leemons-plugin-scores/frontend/src/components/MyScores/components/SubjectsScoreList/components/SubjectScoreColumn/components/Header.js
yarn.lock

1) STUDENT: notebook: In this component, we were only displaying the image (if it existed). Now we display the image, if there is no image we display the colored circle with the icon, and if there is no icon, the initials of the subject.
2) Students and teacher: in kanban and pending activities: We follow the procedure from the previous point in these sections (icon or initials).
3) ONGOING: The same issue as in point 2 occurred. Fixed.
4) Home: Shortcuts to subjects: We adjusted the initials to 22 regular, but in the case of the program indicator, it is set to 14 in Figma (https://www.figma.com/design/Yz6BbVG5JHMue7mTEvcygA/Empty-states?node-id=4429-6379&t=qJSzJFqAhc3UMtXV-1). I understand that 15 is a possible error. I have set it to 14 px.
5) Inconsistency “First Name Last Name” / …

fix: wrong behavior on SubjectAvatar

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/SubjectItemDisplay/SubjectItemDisplay.js
plugins/leemons-plugin-calendar/frontend/src/pages/private/Calendar/index.js

feat(academic-portfolio): added subject name to AvatarSubject in SubjectItemDisplay

fix(calendar): use AvatarSubject as event icon fallback for class events

---

plugins/leemons-plugin-calendar/frontend/src/widgets/user-program-calendar/components/WeekEventList/WeekEventList.js

fix(calendar):
- Order same day events by hour on Calendar Widget events list (Dashboard)

fix(calendar): sort events by start date

---

plugins/leemons-plugin-board-messages/frontend/src/components/DetailDrawer/DetailDrawer.js
plugins/leemons-plugin-board-messages/frontend/src/components/ModalMessage/ModalMessage.js

fix(board-messages): 
- Align buttons on modal view. Change variants and position of  the action buttons.

fix(noticeBoard): align buttons on modal view and modify variants

---

plugins/leemons-plugin-dataset/frontend/src/components/DatasetForm/DatasetForm.js
plugins/leemons-plugin-users/frontend/src/components/UserDataset/UserDatasets.js
plugins/leemons-plugin-users/frontend/src/helpers/dataset.js
plugins/leemons-plugin-users/frontend/src/pages/private/users/DetailUser/UserInfo.js

- Reorder code in DatasetForm for better readability
- Optimize imports and code structure in UserDatasets component
- Improve performance and error handling in dataset helper functions
- Update UserInfo component to use single userAgentId instead of array

refactor(users): optimise dataset handling and user info display

---

plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/index.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/ModuleDashboard.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/DashboardCard.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardCover/DashboardCardCover.js

fix(learning-paths): 
- Add properties to DasboardCard introduction to show cover correctly.

fix(lPaths): Add properties to DashboardCard introduction to show cover

---

plugins/leemons-plugin-dashboard/frontend/src/components/AcademicDashboard/index.js

fix(dashboards): 
- Restore fontSize on ProgramBarSelector component.

fix(dashboards): restore fontSize on `ProgramBarSelector` component.

---

plugins/leemons-plugin-calendar/frontend/src/widgets/user-program-calendar/components/WeekEventList/WeekEventList.js

fix(calendar):
- Order same day events by hour on Calendar Widget events list (Dashboard)

fix(calendar): sort same day events by hour on events list

---

plugins/leemons-plugin-assignables/backend/core/assignations/createAssignation/helpers/comunica/deleteGroupRoom.js
plugins/leemons-plugin-assignables/backend/core/assignations/createAssignation/helpers/comunica/deleteInstanceRoom.js
plugins/leemons-plugin-assignables/backend/core/assignations/createAssignation/helpers/comunica/deleteUserSubjectRoom.js
plugins/leemons-plugin-assignables/backend/core/assignations/createAssignation/helpers/deleteComunicaRooms.js
plugins/leemons-plugin-assignables/backend/core/assignations/getAssignations/getAssignations.js
plugins/leemons-plugin-assignables/backend/core/assignations/removeAssignations/removeAssignations.js
plugins/leemons-plugin-assignables/backend/core/instances/removeInstance/removeInstance.js
plugins/leemons-plugin-assignables/backend/core/permissions/instances/users/removePermissionFromUser.js
plugins/leemons-plugin-assignables/backend/core/teachers/removeTeachersFromAssignableInstance.js
plugins/leemons-plugin-assignables/backend/i18n/en.js
plugins/leemons-plugin-assignables/backend/i18n/es.js
plugins/leemons-plugin-assignables/backend/services/rest/instance.rest.js
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/ActivityHeader.constants.js
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/components/DeleteButton/DeleteButton.js
plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/index.js
plugins/leemons-plugin-assignables/frontend/src/components/Details/Details.js
plugins/leemons-plugin-assignables/frontend/src/components/Details/components/UsersList/helpers/useParseStudents.js
plugins/leemons-plugin-assignables/frontend/src/components/Ongoing/AssignmentList/components/ActivitiesList/ActivitiesList.js
plugins/leemons-plugin-assignables/frontend/src/components/Ongoing/AssignmentList/hooks/useParseAssignations/parseAssignationForStudent.js
plugins/leemons-plugin-assignables/frontend/src/components/Ongoing/AssignmentList/hooks/useParseAssignations/parseAssignationForTeacher.js
plugins/leemons-plugin-assignables/frontend/src/requests/assignableInstances/deleteInstance.js
plugins/leemons-plugin-assignables/frontend/src/requests/hooks/mutations/useDeleteInstance.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/Result/index.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/ModuleDashboard.js

- **feat(assignables): allow teachers to delete activities**
- **feat(assignables): added remove comunica rooms to delete activity pipeline**
- **fix(assignables): recover UnreadMessages column in ongoing**

feat(assignables): added delete activity functionality

---

plugins/leemons-plugin-assignables/frontend/src/widgets/dashboard/nya/components/EvaluationCardStudent/EvaluationCardStudent.js
plugins/leemons-plugin-assignables/frontend/src/widgets/dashboard/nya/components/EvaluationCardStudent/components/ScoreFeedback.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardFooter/DashboardCardFooter.js

fix(assignables):
- ScoreFeedback:  if module has requireScoring property but activities inside module aren't evaluables or punctuables.

fix(assignables): prevent showing NaN on EvaluationCard

---

plugins/leemons-plugin-timetable/frontend/src/components/ScheduleInput/ScheduleInput.js

fix(timetable): 
- ScheduleInput: Order values from weekDay 1 to 6 (from monday to sunday)

fix(timetable): sort ScheduleInput values from monday to sunday

---

plugins/leemons-plugin-assignables/frontend/src/components/NYACard/NYACard.js
plugins/leemons-plugin-assignables/frontend/src/components/NYACard/NYACardSkeleton/NYACardSkeleton.js
plugins/leemons-plugin-assignables/frontend/src/components/NYACard/NYACardSkeleton/NYACardSkeleton.styles.js
plugins/leemons-plugin-assignables/frontend/src/widgets/dashboard/nya/components/ActivityCarousel.js
plugins/leemons-plugin-assignables/frontend/src/widgets/dashboard/nya/index.js

fix(assignables):
- Manage role icon size on NYA Card (footer).
- Refactor styles on NYA Card Skeleton.

fix(assignables): change NYACard icon size and skeleton to match it

---

plugins/leemons-plugin-academic-portfolio/backend/config/constants.js
plugins/leemons-plugin-academic-portfolio/backend/core/reports/getColumns.js
plugins/leemons-plugin-academic-portfolio/backend/core/reports/getData.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/en.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/es.js
plugins/leemons-plugin-academic-portfolio/backend/services/reports.service.js
plugins/leemons-plugin-academic-portfolio/backend/services/rest/reports.rest.js
plugins/leemons-plugin-academic-portfolio/frontend/Private.js
plugins/leemons-plugin-academic-portfolio/frontend/src/config/constants.js
plugins/leemons-plugin-academic-portfolio/frontend/src/hooks/keys/reportKeys.js
plugins/leemons-plugin-academic-portfolio/frontend/src/hooks/queries/useReportColumns.js
plugins/leemons-plugin-academic-portfolio/frontend/src/hooks/queries/useReportData.js
plugins/leemons-plugin-academic-portfolio/frontend/src/pages/private/Reports/index.js
plugins/leemons-plugin-academic-portfolio/frontend/src/pages/private/programs/ProgramsPage.js
plugins/leemons-plugin-academic-portfolio/frontend/src/request/reports/fetchReportColumns.js
plugins/leemons-plugin-academic-portfolio/frontend/src/request/reports/fetchReportData.js

- Add reports page and related components
- Implement backend services for report generation
- Update translations for report-related text
- Add navigation to reports from programs page
- Include new constants for plugin name and version

feat(academic-portfolio): add reports functionality

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/AssetPickerDrawer.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/components/AssetList/AssetList.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/components/AssetList/components/Header.js

…fferent asset lists to make clear that media-files assets are being filter by any type of file, not only images. Remove unused property from AssetList to avoid confusion.

feat(leebrary): added hideMediaFilter prop to AssetList

---

packages/leemons-testing/package.json
scripts/build-all.js
scripts/build-watch-all.js

chore: removed build script from leemons-testing

chore: build and build:watch scipts now will execute on SDKs first

---

plugins/leemons-plugin-grades/frontend/src/components/EvaluationDetail/components/Scales.js
plugins/leemons-plugin-grades/frontend/src/pages/private/Evaluations/EvaluationList.js

fix(grades):
- Order evaluation system table by numbers (from min to max).
- Adjust Description column values styles.

fix(grades): sort evaluation system table by numbers

---

plugins/leemons-plugin-academic-portfolio/frontend/src/widgets/class-detail/index.js
plugins/leemons-plugin-dashboard/frontend/src/pages/private/ClassDashboard/index.js

- Add isChatEnabled check from useComunica hook
- Wrap chat button in conditional rendering
- Update useEffect dependencies

feat(academic-portfolio): conditionally render chat button based on isChatEnabled

---

plugins/leemons-plugin-assignables/frontend/src/components/Assignment/Form.d.ts
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/Form.js
plugins/leemons-plugin-assignables/frontend/src/components/Assignment/components/OtherOptions/OtherOptions.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/Assign/index.js

feat(assignables): added types to FormComponent and set `hideReport` to false by default

fix(feedback): show `hideReport` option when assigning

---

plugins/leemons-plugin-assignables/backend/core/events/afterAddClassTeacher.js
plugins/leemons-plugin-assignables/backend/core/instances/getInstancesStatus/getInstancesStatus.js
plugins/leemons-plugin-assignables/backend/core/permissions/instances/users/addPermissionToUser/addPermissionToUser.js
plugins/leemons-plugin-calendar/backend/core/events/grantAccessUserAgentToEvent.js

fix(assignables): use the right status for non finished activities

fix(assignables): add teachers to activity event when added to class

---

.eslintrc.json
jsconfig.json
packages/leemons-permissions/src/addPermissionsDeploy.js
packages/leemons-react/src/templates/contexts/global.js
packages/leemons-react/src/webpack/webpack.config.js
plugins/leemons-plugin-layout/backend/i18n/en.js
plugins/leemons-plugin-layout/backend/i18n/es.js
plugins/leemons-plugin-layout/frontend/globalContext.js
plugins/leemons-plugin-layout/frontend/package.json
plugins/leemons-plugin-layout/frontend/src/components/ImpersonationLayout.jsx
plugins/leemons-plugin-layout/frontend/src/hooks/useIsOverHeader.js
plugins/leemons-plugin-layout/frontend/src/hooks/useProfile.js
plugins/leemons-plugin-layout/frontend/src/hooks/useUserInfo.js
plugins/leemons-plugin-users/backend/config/constants.js
plugins/leemons-plugin-users/backend/core/profiles/createInitialProfiles/admin.json
plugins/leemons-plugin-users/backend/core/profiles/detailByUri.js
plugins/leemons-plugin-users/backend/core/users/impersonateUser.js
plugins/leemons-plugin-users/backend/i18n/en.js
plugins/leemons-plugin-users/backend/i18n/es.js
plugins/leemons-plugin-users/backend/services/rest/users.rest.js
plugins/leemons-plugin-users/frontend/src/components/UserAdminDrawer/UserAdminDrawer.js
plugins/leemons-plugin-users/frontend/src/hooks/useUserAgents.js
plugins/leemons-plugin-users/frontend/src/pages/protected/Logout/index.js
plugins/leemons-plugin-users/frontend/src/request/hooks/mutations/useImpersonateUser.js
plugins/leemons-plugin-users/frontend/src/request/impersonateUser.js
tsconfig.frontend.json

- **feat(users): allow admins to impersonate other users**
- **feat(users): added impersonation permission**

feat(users): allow admins to impersonate users

---

plugins/leemons-plugin-calendar/frontend/src/pages/private/Calendar/index.js
plugins/leemons-plugin-calendar/frontend/src/widgets/user-program-calendar/components/WeekEventList/components/DayRow/DayRow.js

fix(calendar): Remove logic to show AvatarSubject. Remove comments on DayRow component.

fix(calendar): stop rendering the `AvatarSubject` in all events

---

plugins/leemons-plugin-users/frontend/src/helpers/getUserFullName.js

refactor(users): change getUserFullName. Align this function with  getUserFullName of bubbles to show  Avatar initials in correcto order (surnames, name)

refactor(users): modify `getUserFullName` to be like bubbles'

---

plugins/leemons-plugin-assignables/frontend/src/components/ActivityHeader/index.js

fix(assignables): ActiviyHeader - Menu items are actions for Teacher only.

fix(assignables): hide menu items to students in ActivityHeader

---

plugins/leemons-plugin-learning-paths/backend/core/modules/assignModule.js
plugins/leemons-plugin-learning-paths/backend/services/rest/modules.rest.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/SetupStep.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/components/Config/Config.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/components/Config/components/ConfigAction/ConfigAction.jsx
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/components/Config/components/ConfigAction/index.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/components/Config/components/DeleteAction/DeleteAction.jsx
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/components/Config/components/DeleteAction/index.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/components/Config/components/Duration/Duration.jsx
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/components/Config/components/Duration/index.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/components/Config/components/TypeRenderer/TypeRenderer.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleSetup/components/StructureData/components/ModuleComposer/components/ResourceRenderer/ResourceRenderer.js

- **feat(lModules): added delete activity on assignment action**
- **feat(lModules): modify activity style when deleted**
- **feat(lModules): allow sorting**
- **feat(lModules): disable assign button if non-deleted activities length is < 2**
- **feat(lModules): sort module activities when assigning in the backend**

feat(lModules): add activities sorting and removal in module assignment

---

plugins/leemons-plugin-users/frontend/src/components/UserDetail/UserDetail.js

fix(users): add isChatEnabled condition to show chatButton on UserDetail.js

fix(users): show `chatButton` when `isChatEnabled` in `UserDetail.js`

---

plugins/leemons-plugin-common/backend/core/versionControl/versions/getVersion.js
plugins/leemons-plugin-leebrary/backend/core/permissions/getByCategory/getByCategory.js
plugins/leemons-plugin-leebrary/backend/core/search/byCriteria/filterByPublishStatus.js
plugins/leemons-plugin-leebrary/backend/core/search/byCriteria/getAssetsWithPermissions.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/components/AssetList/components/List.js

even when searching by published status or without criteria
Fixes the bugs of #633

fix(leebrary): only show latest resource version

---

plugins/leemons-plugin-learning-paths/backend/i18n/en.js
plugins/leemons-plugin-learning-paths/backend/i18n/es.js

fix(learning-paths): Change some i18n variables on module setup. "Learning path" to "Content", and "Resources list" to "List".

chore(learning-paths): change i18n values for module setup

---

plugins/leemons-plugin-assignables/frontend/src/components/Ongoing/AssignmentList/hooks/useParseAssignations/parseAssignationForStudent.js
plugins/leemons-plugin-assignables/frontend/src/hooks/useAssignationProgress/constants.js
plugins/leemons-plugin-assignables/frontend/src/hooks/useAssignationProgress/helpers/getSeverity.js
plugins/leemons-plugin-assignables/frontend/src/hooks/useAssignationProgress/helpers/getStatus.js
plugins/leemons-plugin-assignables/frontend/src/hooks/useAssignationProgress/helpers/getStatusName.js
plugins/leemons-plugin-assignables/frontend/src/hooks/useAssignationProgress/index.js
plugins/leemons-plugin-assignables/frontend/src/hooks/useAssignationProgress/useAssignationProgress.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/components/Config/components/ConfigAction/ConfigAction.jsx
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleAssign/components/Config/components/DeleteAction/DeleteAction.jsx
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardFooter/DashboardCardFooter.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardFooter/DashboardCardFooter.styles.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/EvaluationStateDisplay/EvaluationStateDisplay.constants.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/EvaluationStateDisplay/EvaluationStateDisplay.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/EvaluationStateDisplay/EvaluationStateDisplay.styles.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleSetup/components/StructureData/components/ModuleComposer/hooks/useParseActivities.js

the logic was previously in the Ongoing ActivitesList, but now is being reused also in the Modules Dashboard Cards

feat(assignables): abstract useAssignationProgress

---

plugins/leemons-plugin-users/backend/core/providers/listProviders.js
plugins/leemons-plugin-users/backend/core/providers/useProvider.js
plugins/leemons-plugin-users/backend/services/rest/providers.rest.js
plugins/leemons-plugin-users/frontend/src/request/activateProvider.js
plugins/leemons-plugin-users/frontend/src/request/hooks/keys/providers.js
plugins/leemons-plugin-users/frontend/src/request/hooks/mutations/useAddLoginProvider.js
plugins/leemons-plugin-users/frontend/src/request/hooks/queries/useProvidersList.js
plugins/leemons-plugin-users/frontend/src/request/listProviders.js

- **feat(users): added requests to list and activate login provider**
- **feat(users): call provider when installed to initialize it**

eat(users): added requests to list and activate login provider

---

plugins/leemons-plugin-assignables/frontend/src/widgets/dashboard/nya/components/Header.js
plugins/leemons-plugin-assignables/frontend/src/widgets/dashboard/nya/hooks/useNyaStyles.js
plugins/leemons-plugin-calendar/frontend/src/widgets/user-program-calendar/components/WeekEventList/components/DayRow/DayRow.styles.js
plugins/leemons-plugin-calendar/frontend/src/widgets/user-program-calendar/index.js
plugins/leemons-plugin-calendar/frontend/src/widgets/user-program-kanban/index.js

fix(transversal): style widget headers and space between headers and content on dashboard. 
fix(calendar): align datetime events horizontally with event descriptions on user-program-calendar widget

fix:: improvements in Dashboard

---

plugins/leemons-plugin-tests/backend/core/questions-banks/saveQuestionsBanks.js
plugins/leemons-plugin-tests/backend/i18n/en.js
plugins/leemons-plugin-tests/backend/i18n/es.js
plugins/leemons-plugin-tests/backend/validations/forms.js
plugins/leemons-plugin-tests/backend/validations/types.js
plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/Detail.js

…global feedback and responses fields + show validation error messages in front end

fix(tests): remove character restrictions for question banks

---

plugins/leemons-plugin-academic-portfolio/backend/core/classes/classByIds.js

This is needed by https://github.com/leemonade/leemons-private-plugins/pull/130

feat(academic-portfolio): retrieve complete program on getClassByIds

---

plugins/leemons-plugin-users/frontend/src/pages/private/users/ListUsers/index.js

- Use search query value on every data load
- Reset to first data page on any filter change

fix(users): admin users table search errors

---

plugins/leemons-plugin-scores/frontend/src/components/__DEPRECATED__/ScoresPage/Filters/Filters.js

Modify scores page Filters component to accept a teacher type to filter (or not filter at all) classes. This is necessary to list clases in the AttendancePage table of session for an invited teacher.

feat(scores): Add teacher type filter for class listing

---

packages/leemons-cronjobs/src/index.js
packages/leemons-cronjobs/types/index.d.ts

Needed by https://github.com/leemonade/leemons-private-plugins/pull/138

feat(cronjobs): create job manually to allow 'every' method duplications

---

plugins/leemons-plugin-academic-portfolio/frontend/src/pages/private/Reports/index.js
plugins/leemons-plugin-assignables/frontend/src/components/Ongoing/AssignmentList/components/Filters/components/Type/Type.js

fix on Report view with an empty date.

fix(academic-portfolio): Handle empty dates in Reports/index

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/AcademicTree/CourseView/CourseView.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/Tree/SelectUsersForAddToClasses/ByData.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/Tree/SelectUsersForAddToClasses/ByTag.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/Tree/TreeClassroomUsersDetail.js
plugins/leemons-plugin-academic-portfolio/frontend/src/widgets/class-detail/index.js
plugins/leemons-plugin-calendar/frontend/src/components/KanbanTaskCard/KanbanTaskCard.js
plugins/leemons-plugin-users/frontend/src/helpers/getUserFullName.js
plugins/leemons-plugin-users/frontend/src/pages/private/users/CreateUsers/index.js
plugins/leemons-plugin-users/frontend/src/pages/private/users/DetailUser/UserImage.js

fix(transversal): add new param to getFullName helper. Refactor in all components who calls to getFullName to render an Avatar, UserItemDisplay or AvatarsGroup.

fix(transversal): add param to getFullName and update components

---

plugins/leemons-plugin-leebrary/frontend/src/components/LibraryCardEmbed/LibraryCardEmbed.js

- Improved file type determination by using `capitalize` for asset file extensions.
- Updated `Badge` component to disable hover effect for better UI consistency.

fix(library): update file type handling and badge properties on `LibraryCardEmbed`

---

plugins/leemons-plugin-common/frontend/src/components/ChipsContainer.js
plugins/leemons-plugin-leebrary/frontend/src/components/ManageBulkAssets/components/drawers/BulkShareDrawer.js
plugins/leemons-plugin-leebrary/frontend/src/hooks/useBulkAssetsColumns.js

fix(library): truncate tags text to one line. Pass classesData prop with the right property to AvatarsGroup component to show classes on table.

fix(library): improve tag display and class data handling

---

plugins/leemons-plugin-calendar/backend/i18n/en.js
plugins/leemons-plugin-calendar/backend/i18n/es.js
plugins/leemons-plugin-calendar/frontend/src/widgets/user-program-calendar/components/WeekEventList/components/DayRow/DayRow.js

fix(calendar): on Dashboard Calendar, change "task" for "activity on DayWeek panel.

fix(calendar): update task label to activity in DayWeek panel

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/AcademicTree/SubjectView/StudentsTable.js

fix(academic-portfolio): add getFullName function to Avatar on StudentsTable to show initials correctly.

fix(academic-portfolio): fix student initials in StudentsTable

---

plugins/leemons-plugin-tests/frontend/src/pages/private/tests/StudentInstance/index.js

fix(tests): on execution, layout content have to extend to footer.

fix(tests): extend execution layout content to footer

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/AcademicTree/SubjectView/StudentsTable.js
plugins/leemons-plugin-assignables/backend/i18n/en.js
plugins/leemons-plugin-assignables/backend/i18n/es.js
plugins/leemons-plugin-dashboard/frontend/src/components/WelcomeWidget/components/EmptyState/WelcomeCard.styles.js
plugins/leemons-plugin-dashboard/frontend/src/widgets/dashboard/welcome.js

fix(dashboard): styles on WelcomeCards (borders) and add personalized text  with user name on section top.

fix(dashboard): improve WelcomeCard and user personalization

---

plugins/leemons-plugin-assignables/backend/core/events/afterAddClassTeacher.js
plugins/leemons-plugin-assignables/backend/core/teachers/addTeachersToAssignableInstance.js

fix(assignables): pass correct arguments to addTeachersToAssignableInstance

---

plugins/leemons-plugin-scores/backend/i18n/en.js
plugins/leemons-plugin-scores/backend/i18n/es.js
plugins/leemons-plugin-scores/frontend/src/components/EvaluationNotebook/ScoresTable/ScoresTable.js
plugins/leemons-plugin-scores/frontend/src/components/EvaluationNotebook/ScoresTable/hooks/useTableData.js
plugins/leemons-plugin-scores/frontend/src/components/EvaluationNotebook/components/PageFooter/PageFooter.js
plugins/leemons-plugin-scores/frontend/src/components/FinalEvaluationNotebook/FinalEvaluationNotebook.js
plugins/leemons-plugin-scores/frontend/src/components/FinalEvaluationNotebook/hooks/useTableData.js
plugins/leemons-plugin-scores/frontend/src/components/Tables/ScoresBasicTable/ScoreCell/ScoreCell.js
plugins/leemons-plugin-scores/frontend/src/components/Tables/ScoresBasicTable/ScoresBasicTable.js
plugins/leemons-plugin-scores/frontend/src/components/__DEPRECATED__/ScoresPage/Filters/components/SelectPeriod.js
plugins/leemons-plugin-scores/frontend/src/components/__DEPRECATED__/ScoresPage/Filters/hooks/useSelectedPeriod.js
plugins/leemons-plugin-scores/frontend/src/pages/EvaluationNotebookPage.js
plugins/leemons-plugin-tests/frontend/src/widgets/assignables/AssignmentDrawer.js

- **fix(scores): add support for percentage grades**
- **feat(scores): add `full course` option and improve evaluation notebook footer**
- **feat(scores): implement view-only mode for scores tables**
- **fix(tests): use evaluationType auto in assignment drawer**

feat(scores): add full course evaluation and improve scores management

---

plugins/leemons-plugin-academic-portfolio/backend/core/classes/student/remove.js
plugins/leemons-plugin-academic-portfolio/backend/core/classes/student/removeByClass.js
plugins/leemons-plugin-academic-portfolio/backend/core/classes/teacher/removeByClass.js

When classIds is passed as a string it was iterating over the classId string instead of the classIds array.

fix(academic-portfolio): fix classIds iteration and contacts removal

---

packages/leemons-academic-portfolio/src/index.js
plugins/leemons-plugin-academic-portfolio/backend/config/constants.js
plugins/leemons-plugin-academic-portfolio/backend/core/classes/addClassStudents.js
plugins/leemons-plugin-academic-portfolio/backend/core/classes/addClassStudentsMany.js
plugins/leemons-plugin-academic-portfolio/backend/core/classes/addClassTeachers.js
plugins/leemons-plugin-academic-portfolio/backend/core/classes/addClassTeachersMany.js
plugins/leemons-plugin-academic-portfolio/backend/core/classes/updateClass.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/en.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/es.js
plugins/leemons-plugin-academic-portfolio/backend/models/class.js
plugins/leemons-plugin-academic-portfolio/backend/services/rest/class.rest.js
plugins/leemons-plugin-academic-portfolio/frontend/globalContext.js
plugins/leemons-plugin-academic-portfolio/frontend/package.json
plugins/leemons-plugin-academic-portfolio/frontend/src/components/AcademicTree/EnrollmentDrawer/EnrollmentDrawer.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/AcademicTree/SubjectView/EnrollmentTab.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/AcademicTree/SubjectView/EnrollmentTab.styles.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/AcademicTree/SubjectView/SubjectView.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/SubjectSetupDrawer/SubjectSetupDrawer.js
plugins/leemons-plugin-academic-portfolio/frontend/src/config/constants.js
plugins/leemons-plugin-academic-portfolio/frontend/src/context/global.js
plugins/leemons-plugin-academic-portfolio/frontend/src/hooks/mutations/useMutateClass.js
plugins/leemons-plugin-academic-portfolio/frontend/src/pages/private/AcademicTreePage.js
plugins/leemons-plugin-academic-portfolio/frontend/src/pages/private/subjects/SubjectsPage.js

- Added notification system for class and enrolment updates using socket events.
- Improved error handling in class update process.
- Updated i18n files with new socket event messages.
- Refactored class update logic to separate preparation and execution steps.
- Modified frontend components to use new notification system.

feat(academic-portfolio): enhance class update process with notifications and error handling

---

plugins/leemons-plugin-academic-portfolio/backend/core/classes/teacher/add.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/en.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/es.js

- Removed the unnecessary `await` keyword from the `ctx.emit('after-add-class-teacher', {...})` call in the `add` function to improve performance.
- Updated English and Spanish i18n files to provide more detailed messages for long-running operations.

fix(academic-portfolio): remove unnecessary await in add function in `addTeacher` action function

---

packages/leemons-users/src/types.d.ts
plugins/leemons-plugin-menu-builder/backend/core/menu/getIfHasPermission.js
plugins/leemons-plugin-users/backend/core/profiles/getProfileByUserAgent.js
plugins/leemons-plugin-users/backend/core/user-agents/getUserAgentProfile.js
plugins/leemons-plugin-users/backend/services/profiles.service.js

This Pull Request addresses issues with menu permission checks and improves profile handling.
- Refactored `getIfHasPermission` to use profile permissions instead of user permissions.
- Updated `getUserAgentProfile` to return a `Profile` type.
- Added `detailByUserAgent` action in `profiles.service.js` for fetching profile details.
- Introduced `ProfileID` and `Profile` types in `types.d.ts`.

fix(menu-permissions): update permission handling logic

---

plugins/leemons-plugin-common/frontend/globalContext.js
plugins/leemons-plugin-common/frontend/src/components/ContentEditorInput/ContentEditorInput.js
plugins/leemons-plugin-common/frontend/src/components/ContentEditorInput/components/TextEditorContent/TextEditorContent.js

- Added `toolbar` property to text editor tools in `globalContext.js`.
- Utilized `useMemo` for `leemonsTools` in `ContentEditorInput.js` to optimize performance.
- Updated `leemonsTools` prop to be passed directly as a memoized value.
- Minor code cleanup in `TextEditorContent.js`.

feat: enhance text editor tool management

---

plugins/leemons-plugin-academic-portfolio/backend/i18n/en.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/es.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/AcademicTree/SubjectView/CustomPeriod.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/AcademicTree/SubjectView/SubjectView.js

- Handle the correct response type for the useAcademicCalendarConfig hook 
- Add success alert when updating a subject custom period

fix(academicPortfolio): Fix Custom Period component 

---

jsconfig.json
plugins/leemons-plugin-academic-portfolio/backend/core/reports/getColumns.js
plugins/leemons-plugin-academic-portfolio/backend/core/reports/getData.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/en.js
plugins/leemons-plugin-academic-portfolio/backend/i18n/es.js
plugins/leemons-plugin-academic-portfolio/frontend/src/pages/private/Reports/index.js
tsconfig.frontend.json

- Enhance reports data retrieval to include teacher and student tags
- Update column definitions and frontend rendering to support tag display
- Add internationalization support for new tag columns
- Modify getData method to fetch and attach user agent tags dynamically

feat(academic-portfolio): Add user agent tags to reports
