plugins/leemons-plugin-layout/backend/i18n/en.js
plugins/leemons-plugin-layout/backend/i18n/es.js
plugins/leemons-plugin-layout/frontend/globalContext.js

We have fixed the modal logic to display the message body. We have also placed the new title and body of the message and their corresponding translations.

Library - Texto en modal de duplicar

---

plugins/leemons-plugin-tests/frontend/src/pages/private/tests/Edit.js

Fix test can't be published once saved as draft.
The problem was the tests frontend was sending full cover url instead of cover id.

Test: send right cover data to assignables

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetSetup/components/PermissionsDataUsers.js

The original code has the property `editMode` switched: is true when it should be false, and viceversa.
The TableInput needs to forceShowInputs and to be editable when we are in real editMode `!editMode`

fix(leebrary): show inputs in share with users modal

---

plugins/leemons-plugin-leebrary/backend/core/assets/update/handleFileAndCoverUpdates.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetForm/AssetForm.js
plugins/leemons-plugin-leebrary/frontend/src/helpers/prepareAsset.js
plugins/leemons-plugin-leebrary/frontend/src/pages/private/assets/AssetPage.js

- asset cover can be changed correctly
- asset file updates work correctly, only one file per asset 
- bookmarks save and update cover image correctly
- when editing, the cover value sent to de backend is a file id or null/undefined not a url

fix(leebrary): Files & cover files management when editing/creating a media-files or bookmark asset

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/components/NewResource.js

Pass indexable parameter as false when creating an asset through the AssetPickerDrawer in order for it not to be listed in library.

fix(library): set assets created through the AssetPickerDrawer as no indexable

---

plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleSetup/components/Resources/Resources.js

...to show assets as a list instead of a grid

fix(learning-paths): change AssetPickerDrawer layout to rows 

---

packages/leemons-cache/src/types/redis/index.js

When no redis config was provided, nor CACHE_REDIS_URI, it was trying to use defaultConfig with empty URI, so it won't fallback for node-cache, and failed to connect redis to undefined URI.

fix(leemons-cache): ensure that local node-cache is used if no redis config is provided

---

plugins/leemons-plugin-content-creator/backend/config/constants.js

dashboardURL is used for the student redirection to a dashboard of the activity, such as module dashboard, not to redirect it to the evaluation, review or execution pages

fix(CCreator): remove dashboardURL

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetEmbedList.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPlayer/AssetPlayer.js

When a media change, set showPlayer state to false.  The issue we were having is that when an asset is of type video or audio and we played it, the showPlayer variable remained set to true, applying a pointerEvents: none to the parent layer that stayed set when we switched assets, preventing any clicks on the new asset whenever it was of a media type. With this implementation, we fixed the bug.

Asset Drawer - Extraño comportamiento

---

plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleSetup/components/BasicData/BasicData.js

SharedValues object is managed differently for it not to reset the form but set its values. This ensures the name field will not cause a form reset. Data from the server still loads correctly on edition.

fix(learning-paths): Title changes don't reset the form

---

plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/components/DetailQuestionForm.js
plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/components/DetailQuestions.js
plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/components/question-types/MonoResponse/components/ListInputRender.js
plugins/leemons-plugin-tests/frontend/src/pages/private/questions-banks/components/question-types/MonoResponse/index.js

+ add margin to the box that renders the ListInputRender for the add answer button to always be visible, even when the answers contain images.

fix(tests): scroll to the input element when adding answers in MonoResponse question types

---

plugins/leemons-plugin-assignables/backend/models/grades.js

The unique index will avoid grade duplication problems where multiple requests were overlapiing.
Ticket: issue/Transversal-87

fix(assignables): add unique index to grades schema

---

.eslintrc.json
package.json
yarn.lock

Recently I've seen so many hooks being called outside of components/other hooks, missing dependencies causing unexpected errors, or other bad practices, so I've added the react-hooks esline plugin to show the best practices while coding.

chore: add react-hooks eslint plugin

---

packages/leemons-deployment-manager/src/getDeploymentID.js
plugins/leemons-plugin-assignables/backend/core/instances/sendEmail/sendEmail.js

- Implement query parameter check for deploymentID before falling back to domain-based retrieval.
- Refactor `sendEmail` function in "leemons-plugin-assignables" to use `getCoverAndAvatarUrls` for URL generation, improving code reuse and maintainability.

feat(deployment-manager): enhance deploymentID retrieval logic

---

plugins/leemons-plugin-tests/frontend/src/components/QuestionImage.js

fix(QuestionImage): If user uses clue on map, the marker got opacity at 0.5

Test - mapa - Marker disabled

---

plugins/leemons-plugin-leebrary/backend/core/search/byCriteria/byCriteria.js
plugins/leemons-plugin-leebrary/backend/core/search/byCriteria/getProviderAssets.js
plugins/leemons-plugin-leebrary/backend/models/assets.js
plugins/leemons-plugin-leebrary/backend/services/rest/assets.rest.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetForm/AssetForm.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetList.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/AssetPickerDrawer.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPickerDrawer/components/NewResource.js
plugins/leemons-plugin-leebrary/frontend/src/components/ImagePicker.js
plugins/leemons-plugin-leebrary/frontend/src/pages/private/assets/ListAssetPage.js

- Bring back normal recents behavior.
- Store isCover property in asset creation in order to differentiate assets created as covers and be able to filter them from the recents section of the library

fix(leebrary): bring back normal recents behavior + differenciate cover assets from regular ones by the way the are created

---

.gitignore
.vscode/extensions.json
.vscode/settings.json

Add basic VSCode configuration so the entire team can share a more consistent work experience:
- List of recommended extensions.
> If you open the project in VSCode, a notification suggesting you to install recommended extension should appear. Docs: https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions
- Formatting settings for all files.
> Open any file and save it. If the linter or formatter finds any errors, all auto-fixable ones will be automatically fixed.

chore(vscode): initial standardization of configuration

---

plugins/leemons-plugin-admin/frontend/src/pages/private/Setup/index.js
plugins/leemons-plugin-deployment-manager/frontend/src/hooks/useDeploymentConfig.js

- Wrap navigation logic inside useEffect to handle redirects based on deploymentConfig changes in `leemons-plugin-admin` Setup page.
- Update `useDeploymentConfig` hook to include `pluginName` and `ignoreVersion` parameters for more precise deployment configurations.
- Update subproject reference to include latest changes.

feat: enhance navigation with useEffect in Setup page

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetForm/AssetForm.js
plugins/leemons-plugin-leebrary/frontend/src/components/CardWrapper.js

fix(test): 
- If delete image preview, card preview image remove too.
- card preview cursor fixed.
- If delete the image asset, preview card return to skeleton (as first render). 
- Fix spanish translations of "Remove" button to "Borrar"

Resources - Creation - Card Vista previa ajustes

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/EnrollUserSummary/EnrollUserSummary.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/EnrollUserSummary/components/SubjectWithClassroomDisplay.js

- Use lodash's `compact` to remove falsy values from arrays
- Safely access nested properties using optional chaining
- Trim and clean up course names
- Join name parts more robustly in `getTeacherFullname`
- Make `getTeachersIds` more defensive by handling missing data

fix(academic-portfolio): handle missing data on `EnrollUserSummary`

---

plugins/leemons-plugin-leebrary/frontend/src/components/AssetForm/AssetForm.js

fix(leebrary): add subtitle to "Presentation" section on AssetForm.

Assets - Creation - Falta Label de imagen destacada en presentación 

---

plugins/leemons-plugin-academic-portfolio/frontend/src/widgets/user-classes-swiper/index.js
plugins/leemons-plugin-leebrary/backend/core/assets/duplicate/handleAssetDuplication.js
plugins/leemons-plugin-leebrary/backend/core/assets/update/update.js
plugins/leemons-plugin-leebrary/frontend/src/hooks/useIsOwner.js
plugins/leemons-plugin-tests/backend/core/questions-banks/listQuestionsBanks.js
plugins/leemons-plugin-tests/backend/core/tests/duplicate.js
plugins/leemons-plugin-tests/backend/core/tests/saveTest.js
plugins/leemons-plugin-tests/backend/services/rest/questionsBanks.rest.js
plugins/leemons-plugin-tests/backend/services/rest/tests.rest.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/components/DetailQuestionsBanks.js
plugins/leemons-plugin-tests/frontend/src/request/tests/index.js
plugins/leemons-plugin-tests/frontend/src/widgets/leebrary/TestsDetail.js
plugins/leemons-plugin-tests/frontend/src/widgets/leebrary/TestsListCard.js

- Allow duplicating tests with option to keep or duplicate question bank
- Improve test saving to handle asset and subject ignoring
- Update question bank listing to include assets and check ownership
- Enable test sharing for published tests owned by user
- Refactor `useIsOwner` hook to handle asset creation ownership
- Update frontend to duplicate tests based on ownership
- Improve class swiping widget to format group and course names

feat(tests): improve test duplication and question bank handling

---

plugins/leemons-plugin-common/frontend/src/LocaleDate.js
yarn.lock

Add LocaleWeekDay function to format weekdays based on locale
- Introduced `LocaleWeekDay` function to format and return the name of the weekday based on the user's locale.
- Utilizes `Intl.DateTimeFormat` for locale-specific formatting.
- Adjusts the reference date to match the desired day of the week.

feat(LocaleDate): add LocaleWeekDay function to format weekdays

---

plugins/leemons-plugin-widgets/backend/core/widgetZone/get.js
plugins/leemons-plugin-widgets/backend/services/widgets.service.js

- Added call to `deployment-manager.getConfigRest` to fetch deployment configuration.
- Filtered out denied zones and items based on the deployment configuration.
- Ordered allowed widget items by their `order` property.
- Removed unnecessary MongoDB connection in `widgets.service.js`.

feat(widgets): hide widgets based on deployment configuration

---

plugins/leemons-plugin-academic-portfolio/frontend/src/components/AcademicTree/SubjectView/EnrollmentTab.js
plugins/leemons-plugin-academic-portfolio/frontend/src/hooks/keys/classStudents.js
plugins/leemons-plugin-academic-portfolio/frontend/src/hooks/mutations/useMutateClass.js
plugins/leemons-plugin-academic-portfolio/frontend/src/hooks/queries/useClassStudents.js

Implement useClassStudents hook to be able to manage states separately for the user not to lose not saved changes when filling the EnrollmentTab form (in AcaTree) and enrolling students at the same time.
- This is a temporary fix as backend changes are "forbiden" temporarly. Once we can make changes in backend a new rest action should be created to bring only the desired data.

fix(academic-portfolio): Allow user to preserve not saved changes when modifying the subject and enrolling students at the same time. 

---

plugins/leemons-plugin-calendar/frontend/src/widgets/calendar/task.js

fix(calendar): on Event detail drawer of Kanban, show "subtask" header on subtasks section.

Kanban-Drawer falta titular de subtareas

---

plugins/leemons-plugin-academic-portfolio/backend/core/groups/getGroupById.js
plugins/leemons-plugin-academic-portfolio/backend/core/programs/getAcademicTree.js

It changes only academic-portfolio plugin.
- Groups retrieval in cases where a program with non-sequential courses has reference groups 
- Compare strings with localCompare when ordering groups for the AcademicTree

Academic Portfolio groups minor issues

---

plugins/leemons-plugin-tests/frontend/src/components/AssetMetadataTest/AssetMetadataTest.js

fix(leebrary): on Test detail, remove QBank link. Show only informative QB name.

MainLibrary - Tests - Detail Drawer - Quitar enlace a QBank

---

plugins/leemons-plugin-content-creator/frontend/src/widgets/leebrary/DocumentListCard.js
plugins/leemons-plugin-feedback/frontend/src/widgets/leebrary/FeedbackListCard.js
plugins/leemons-plugin-learning-paths/frontend/src/widgets/leebrary/ListCard.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetPlayer/AssetPlayer.js
plugins/leemons-plugin-leebrary/frontend/src/components/CardWrapper.js
plugins/leemons-plugin-tasks/frontend/src/widgets/leebrary/ListCard.js
plugins/leemons-plugin-tests/frontend/src/widgets/leebrary/QuestionsBanksListCard.js
plugins/leemons-plugin-tests/frontend/src/widgets/leebrary/TestsListCard.js

Add "active" color border to this asset cards:
- C.Creator
- Tasks
- Tests
- QBank
- Surveys
- Modules
In audio resources, remove centered play button if audio is playing.

Main Library - Faltan estados “activos” de cards en algunas tipologías

---

plugins/leemons-plugin-board-messages/frontend/src/components/MessagesTable/MessagesTable.js
plugins/leemons-plugin-board-messages/frontend/src/pages/private/List/index.js

Update MessagesTable and List components to use profiles from useProfiles hook
- Set default value for `setProfiles` in `MessagesTable` component
- Add `useProfiles` hook to fetch profiles in List component
- Filter out admin profiles and map to label-value pairs
- Replace `store.profiles` with `profileItemsWithoutAdmin` in List component
- Remove setProfiles function from List component

feat(board-messages): Remove "Admin" from eligibles profiles

---

apps/dev/moleculer.config.js
plugins/leemons-plugin-bulk-data/backend/core/importHandlers/getLoadStatus.js
plugins/leemons-plugin-bulk-data/backend/core/importHandlers/importBulkData.js
plugins/leemons-plugin-bulk-data/backend/core/importHandlers/loadTemplateFromUrl.js
plugins/leemons-plugin-bulk-data/backend/core/leebrary.js
plugins/leemons-plugin-bulk-data/backend/core/tasks.js
plugins/leemons-plugin-bulk-data/backend/core/tests.js
plugins/leemons-plugin-bulk-data/backend/services/bulk.service.js
plugins/leemons-plugin-bulk-data/backend/services/rest/bulk.rest.js
plugins/leemons-plugin-calendar/backend/services/deploy.service.js

- Added `initOnPhase` parameter to `getLoadProgress` and `getLoadStatus` for phase initialization.
- Updated `importBulkData` to include `onFinishData` and emit `finish-load-template` event.
- Modified `loadFromTemplateURL` to handle `onFinishData` and return true.
- Enhanced `initLibrary`, `initTasks`, and `initTests` to support caching and progress tracking.
- Added `loadFromTemplateURL` action to bulk service.
- Fixed event name in calendar deploy service.

feat(bulk-data): enhance bulk data import with caching and progress tracking

---

plugins/leemons-plugin-assignables/backend/core/instances/createInstance/createEventAndAddToUsers.js
plugins/leemons-plugin-calendar/backend/core/calendar/getCalendarsToFrontend.js
plugins/leemons-plugin-calendar/backend/core/kanban-columns/list.js
plugins/leemons-plugin-calendar/frontend/src/components/calendar-event-modal.js
plugins/leemons-plugin-calendar/frontend/src/pages/private/Calendar/index.js
plugins/leemons-plugin-calendar/frontend/src/request/getCalendarsToFrontend.js
plugins/leemons-plugin-calendar/frontend/src/widgets/user-program-calendar/index.js

- Updated `getCalendarsToFrontend` to accept `showHiddenColumns` parameter.
- Modified `list` function to filter kanban columns based on `showHiddenColumns` flag.
- Adjusted frontend components and requests to include `showHiddenColumns` parameter.
- Enhanced documentation for better clarity on new parameter usage.

feat(calendar): add support for showing hidden columns in calendar views

---

plugins/leemons-plugin-tests/frontend/src/pages/private/tests/components/DetailQuestions.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/components/FinalDropdown.js

fix(tests): In creation or edit mode, if user don't select any questions, disable footer buttons to prevent a tests without questions

fix(tests): disable footer buttons if no question selected in the test

---

plugins/leemons-plugin-feedback/backend/i18n/en.js
plugins/leemons-plugin-feedback/backend/i18n/es.js
plugins/leemons-plugin-feedback/frontend/src/widgets/leebrary/FeedbackDetail.js
plugins/leemons-plugin-feedback/frontend/src/widgets/leebrary/FeedbackListCard.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetSetup/PermissionsData.js
plugins/leemons-plugin-leebrary/frontend/src/components/AssetSetup/components/PermissionsDataUsers.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryDetailContent/LibraryDetailContent.js
plugins/leemons-plugin-tasks/frontend/src/widgets/leebrary/Detail.js
plugins/leemons-plugin-tests/frontend/src/widgets/leebrary/QuestionsBanksDetail.js
plugins/leemons-plugin-tests/frontend/src/widgets/leebrary/QuestionsBanksListCard.js
plugins/leemons-plugin-users/frontend/src/components/SelectUserAgent.js

Some assets can't share with students (only between teachers). 
Remove double border on asset in Permission Drawer (Libary embed card must have only one border)
Permissions tab on Detail drawer must show user image (if exist).

feat(leebrary): Allow asset sharing on every asset type

---

plugins/leemons-plugin-leebrary/frontend/src/helpers/uploadFileAsMultipart.js
plugins/leemons-plugin-scorm/frontend/src/pages/Detail/index.js

- Adds a parameter to the uploadFileAsMultlipart to specify when a zip file should be understood as a folder.
- It defaults to false and it is only passed as true in the savePackage function of the Scorm plugin.
**NOTE:** If SCORM creation is intended to occur only on the SCORM creation page, this fix should suffice. However, if SCORM creation (uploading a zip as a folder) is required elsewhere in the application, such as in the asset drawer, it must be specifically implemented there.

fix(leebrary): stop uploading `zip`s as `directories` by default

---

plugins/leemons-plugin-content-creator/backend/i18n/en.js
plugins/leemons-plugin-content-creator/backend/i18n/es.js
plugins/leemons-plugin-content-creator/frontend/src/pages/Detail/index.js
plugins/leemons-plugin-feedback/backend/i18n/en.js
plugins/leemons-plugin-feedback/backend/i18n/es.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/Preview/index.js
plugins/leemons-plugin-learning-paths/frontend/src/components/ModuleDashboard/components/DashboardCard/components/DashboardCardFooter/DashboardCardFooter.js
plugins/leemons-plugin-tasks/backend/i18n/en.js
plugins/leemons-plugin-tasks/backend/i18n/es.js
plugins/leemons-plugin-tasks/frontend/src/components/Student/TaskDetail/TaskDetail.js
plugins/leemons-plugin-tasks/frontend/src/components/Student/TaskDetail/components/StepContainer/StepContainer.js
plugins/leemons-plugin-tasks/frontend/src/components/Student/TaskDetail/components/SubmissionStep/SubmissionStep.js
plugins/leemons-plugin-tests/backend/i18n/en.js
plugins/leemons-plugin-tests/backend/i18n/es.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/Detail.js
plugins/leemons-plugin-tests/frontend/src/pages/private/tests/StudentInstance/components/QuestionList.js

fix(transversal): on a module preview, if user enter on a atom preview, show button to go back to module preview dashboard

feat: Added `Go to dashboard` button on module's sub-activities previews

---

plugins/leemons-plugin-tests/frontend/src/pages/private/tests/components/DetailQuestionsBanks.js

fix(tests): add pageSize equal to 100 for listQuestionBanksRequest and solve the problem if user select a QBank on a page different of first (10 results) and when enter on edit mode, system can't find the selected QBank.

fix(tests): modified query size to 100 temporarily

---

plugins/leemons-plugin-content-creator/frontend/src/pages/Detail/index.js

fix(content-creator): Move "goBackToDashboard" button to "rightZone" prop in TotalLayoutHeader

fix(cCreator): Move `goBackToDashboard` button to `rightZone` prop

---

plugins/leemons-plugin-users/frontend/src/components/UserAdminDrawer/UserAdminDrawer.js
plugins/leemons-plugin-users/frontend/src/components/UserForm.js

In UserAdminDrawer and UserForm components
- Added `handleActivateUser` function in `UserAdminDrawer` to update user activation status.
- Passed `onActivateUser` prop to `UserForm` to handle user activation.
- Updated `UserForm` to call `onActivateUser` on user activation success or failure.
- Updated prop types in `UserForm` to include `onActivateUser`.

fix(user): Add user activation handling

---

scripts/exportBulkTemplates.js

- Remove logs and improve comments for the use of the `exportBulkTemplates` script
- Set a clearer name for local databases holding the deployments for the different templates (these are currently the source of truth, as they have been updated locally and differ from the original production deployments).

feat(scripts): exportBulkTemplates

---

plugins/leemons-plugin-users/frontend/src/components/SelectUserAgent.js
plugins/leemons-plugin-users/frontend/src/pages/private/roles/DetailRoles/index.js

- Updated `SelectUserAgent.js` to use optional chaining for `user.name` and `user.surnames` properties.
- Updated `DetailRoles/index.js` to use optional chaining for `user.name` and `user.surnames` properties.
- Updated submodule `private-plugins` to the latest commit.

fix(users): add optional chaining to user properties

---

packages/leemons-emails/src/emails/EmailLayout.jsx
plugins/leemons-plugin-assignables/backend/emails/UserNewAssignation.jsx
plugins/leemons-plugin-assignables/backend/emails/UserRememberAssignation.jsx
plugins/leemons-plugin-leebrary/backend/core/permissions/set/addPermissionsToUserAgent.js
plugins/leemons-plugin-users/backend/emails/NewProfileAdded.jsx
plugins/leemons-plugin-users/backend/emails/RecoverPassword.jsx
plugins/leemons-plugin-users/backend/emails/ResetPassword.jsx
plugins/leemons-plugin-users/backend/emails/TeacherAssigmentsGuideFree.jsx
plugins/leemons-plugin-users/backend/emails/TeacherEvaluationGuideFree.jsx
plugins/leemons-plugin-users/backend/emails/TeacherFirstStepsGuideFree.jsx
plugins/leemons-plugin-users/backend/emails/Welcome.jsx

- Moved PropTypes import to the correct position in various email components.
- Updated logo URL in EmailLayout.jsx.
- Removed `[Leemons]` prefix from previewText in multiple email components.
- Enhanced error message in addPermissionsToUserAgent.js to include role details.
BREAKING CHANGE: The logo URL in EmailLayout.jsx has been hardcoded, and the previewText format has been changed.

fix(emails): update email components and layout

---

plugins/leemons-plugin-calendar/backend/core/events/updateFromUser.js

…ns to an event for an user that already has it.

fix(calendar): Prevent throwing when event permissions already exist

---

plugins/leemons-plugin-feedback/backend/core/feedback/duplicateFeedback.js

Questions are no longer lost when duplicating a survey with a featured image.
Updating the previously duplicated assignable was causing a new version to be created, resulting in the new survey’s questions pointing to the wrong assignable version.
This fix prevents the creation of new assignable versions while maintaining the existing logic to determine whether the duplicated survey is published. Currently, this is defined by a parameter from the frontend set to true

fix(feedback): survey questions were not duplicated with the feedback

---

plugins/leemons-plugin-assignables/frontend/src/components/Details/components/UsersList/StudentsList/StudentsList.js
plugins/leemons-plugin-assignables/frontend/src/hooks/assignableInstance/usePendingEvaluationsCount.js

fix(assignables): usePendingEvaluationsCount refactor to count activities with one or more evaluation pending. StudentsList remove sticky error on table header. No need to have a sticky header because when list exceed from 10 users, pagination prevent excesive items on list.

fix(assignables): the modules NYA card does not track pending evaluation

---

.eslintrc.json
jsconfig.json
packages/leemons-react/src/webpack/webpack.config.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/Result/index.js
plugins/leemons-plugin-feedback/frontend/src/pages/private/feedback/StudentInstance/components/QuestionsStep.js
plugins/leemons-plugin-feedback/frontend/src/widgets/assignables/AssignmentDrawer.js
tsconfig.frontend.json

When the student finished a feedback it was always redirected to the results page, which throws an error if is disabled for students.
Now it redirects correctly to the results page if is enabled, otherwise to the module dashboard if is a module or to the ongoing activities.
fix(feedback): module assignments hide results by default
fix(feedback): show next activity url in the results page

fix(feedback): redirect student to the expected page

---

plugins/leemons-plugin-academic-portfolio/frontend/src/widgets/class-detail/index.js

- Prevents users from seeing the chat button when viewing their own profile in the class detail widget.
- Also adds chat functionality for teachers.

feat(academic-portfolio): hide chat button for self-messaging

---

plugins/leemons-plugin-leebrary/frontend/src/components/LibraryTool/LibraryModal.js

fix(leebrary): If on content creator, user select an image or video to insert in the document, default display must be "player"

fix(leebrary): add image and video as player by default in LibraryTool

---

plugins/leemons-plugin-leebrary/backend/core/search/byCriteria/filterByPublishStatus.js

filterByPublishStatus always returns strings now so uniqBy(assets, 'asset') was failing

fix(leebrary): return unique assets from filterByPublishStatus

---

plugins/leemons-plugin-leebrary/frontend/src/components/LibraryCardCC/components/LibraryCardCCFooter/LibraryCardCCFooter.js
plugins/leemons-plugin-leebrary/frontend/src/components/LibraryTool/LibraryModal.js

fix(leebrary): Content creator. Audio resources, video resources and bookmarks as video, default display: player. Remove logs from LibraryCardCCFooter

fix(leebrary): set default player display for media resources

---

plugins/leemons-plugin-leebrary/frontend/src/pages/private/assets/BulkAssetPage.js

fix(leebrary): pass "t" param from BulkAssetPage to ManageBulkAssets component. ManageBulkAssets is waiting to this prop and thow an error because the component and his childrens can't find this prop.

fix(leebrary): pass translation prop to bulk assets components

---

plugins/leemons-plugin-menu-builder/backend/core/menu/getIfHasPermission.js

Refactored the `getIfHasPermission` function to eliminate the use of regex in the `type` query, improving performance by directly using the `typeTemplate` string. This change ensures more efficient permission checks for menu items.

fix(menu-builder): remove unnecessary regex from permission query

---

plugins/leemons-plugin-academic-portfolio/backend/core/classes/updateClass.js
plugins/leemons-plugin-academic-portfolio/frontend/globalContext.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/AcademicTree/SubjectView/SubjectView.js
plugins/leemons-plugin-academic-portfolio/frontend/src/components/SubjectSetupDrawer/SubjectSetupDrawer.js
plugins/leemons-plugin-academic-portfolio/frontend/src/hooks/mutations/useMutateClass.js

- Updated `emitUpdateClassEvent` to include `classWithoutGroupId` in the emitted data.
- Modified `getClassName` to prioritize `classWithoutGroupId` when determining class name.
- Adjusted `SubjectView` and `SubjectSetupDrawer` components to handle `classWithoutGroupId`.
- Enhanced `useMutateClass` hook with optimistic updates and error handling for class updates.

fix(academic-portfolio): update class handling to include classWithoutGroupId
